/* UnseenGo AI — accommodation discovery layer. Prices are indicative bands, not live rates. */
const stayData={
 Hyderabad:[['Old City / Charminar','Heritage stays','₹1,000–₹3,000','Best for historic atmosphere and Old City access.'],['Banjara Hills','Boutique & premium','₹3,000–₹8,000+','Good for restaurants, shopping and a more upscale stay.'],['HITEC City','Business hotels','₹2,500–₹7,000+','Convenient for technology districts and modern amenities.'],['Necklace Road / Tank Bund','Mid-range hotels','₹2,000–₹5,000','Useful for lakefront access and central sightseeing.']],
 Bengaluru:[['MG Road / Central Bengaluru','Hotels & boutique stays','₹2,000–₹7,000+','Central base for heritage, shopping and city transport.'],['Indiranagar','Boutique & lifestyle stays','₹2,500–₹8,000+','Great for cafés, nightlife and local neighbourhood experiences.'],['Koramangala','Budget to premium','₹1,500–₹6,000+','Popular for food, cafés and younger travellers.'],['Whitefield','Business hotels','₹2,500–₹8,000+','Convenient for IT parks and longer business stays.']],
 Chennai:[['Mylapore','Heritage & boutique stays','₹1,500–₹5,000','Good base for temples, traditional streets and food trails.'],['T. Nagar','Hotels & budget stays','₹1,500–₹6,000+','Shopping, food and central connectivity.'],['Marina / Triplicane','Budget & mid-range','₹1,200–₹4,500','Convenient for Marina Beach and historic central Chennai.'],['ECR','Resorts & beach stays','₹3,000–₹10,000+','Better for a relaxed coastal experience outside the core city.']],
 Mumbai:[['Colaba','Heritage & premium','₹3,000–₹12,000+','Ideal for Gateway of India, Fort and waterfront heritage.'],['Fort / Churchgate','Business & boutique','₹3,000–₹10,000+','Central for heritage walks and South Mumbai.'],['Bandra','Boutique & lifestyle','₹3,000–₹10,000+','Good for cafés, nightlife and coastal neighbourhoods.'],['Andheri','Budget to premium','₹2,000–₹8,000+','Wide range of accommodation and transport connections.']],
 Pune:[['Shivajinagar','Budget to mid-range','₹1,500–₹5,000','Central base for heritage and city exploration.'],['Koregaon Park','Boutique & premium','₹2,500–₹9,000+','Cafés, restaurants and relaxed neighbourhood atmosphere.'],['Camp','Heritage & mid-range','₹1,800–₹6,000','Useful for old Pune, food trails and shopping.'],['Hinjewadi','Business stays','₹2,000–₹7,000+','Best for technology/business visits.']],
 Kolkata:[['Park Street','Hotels & premium','₹2,500–₹9,000+','Central for food, nightlife and colonial-era landmarks.'],['Esplanade / New Market','Budget to mid-range','₹1,200–₹5,000','Convenient for central sightseeing and markets.'],['Salt Lake','Business & modern stays','₹2,000–₹7,000+','Good for business travel and planned neighbourhoods.'],['North Kolkata','Heritage neighbourhood stays','₹1,500–₹5,000','Useful for Kumartuli and old-city culture.']],
 Jaipur:[['Old City / Pink City','Heritage stays','₹1,000–₹6,000+','Best for forts, bazaars, food and historic atmosphere.'],['C-Scheme','Boutique & premium','₹2,500–₹9,000+','Central, modern and convenient for restaurants.'],['Amer','Heritage & resort stays','₹2,500–₹10,000+','Good for a slower fort-focused trip.'],['Malviya Nagar','Budget to mid-range','₹1,500–₹5,000','Practical base with shopping and transport options.']],
 Ahmedabad:[['Old City','Heritage stays','₹1,000–₹4,000','Best for pols, markets and historic architecture.'],['Navrangpura','Hotels & business stays','₹1,800–₹6,000','Central and convenient for food and city travel.'],['Satellite / Prahlad Nagar','Modern & premium','₹2,500–₹8,000+','Good for restaurants, shopping and modern amenities.'],['Gandhinagar','Business & premium','₹2,000–₹7,000+','Useful when combining Ahmedabad with Gandhinagar sights.']],
 Lucknow:[['Hazratganj','Boutique & premium','₹2,000–₹8,000+','Central for shopping, food and heritage exploration.'],['Chowk / Old Lucknow','Heritage & budget','₹1,000–₹4,000','Closest to Awadhi food and historic lanes.'],['Gomti Nagar','Modern hotels','₹2,000–₹8,000+','Contemporary district with restaurants and business facilities.'],['Charbagh','Budget & transit stays','₹1,000–₹4,500','Practical for railway access and short visits.']],
 Bhubaneswar:[['Old Town','Heritage & budget','₹1,000–₹4,000','Good for temples and the historic core.'],['Jaydev Vihar','Mid-range & business','₹1,800–₹6,000','Central and convenient for modern Bhubaneswar.'],['Patia','Modern & business stays','₹2,000–₹7,000+','Useful for IT/business areas and longer stays.'],['Puri Road corridor','Mid-range hotels','₹1,500–₹5,000','Convenient for combining Bhubaneswar and nearby attractions.']],
 Kochi:[['Fort Kochi','Heritage & boutique','₹1,500–₹7,000+','Best for heritage streets, art, cafés and waterfront culture.'],['Mattancherry','Heritage & budget','₹1,000–₹4,500','Good for palace, spice-market and historic neighbourhood access.'],['Ernakulam','Hotels & business stays','₹1,500–₹6,000+','Practical transport hub with many accommodation choices.'],['Vypin','Beach & relaxed stays','₹1,500–₹6,000','Quieter option for coastal experiences.']],
 Varanasi:[['Assi Ghat','Guesthouses & boutique stays','₹800–₹5,000+','Popular base for riverfront walks and a relaxed atmosphere.'],['Godowlia / Old City','Budget & heritage stays','₹700–₹4,000','Close to major ghats, markets and temples.'],['Cantonment','Hotels & premium','₹2,000–₹9,000+','More spacious modern hotel options.'],['Sarnath','Quiet stays','₹1,000–₹4,500','Best for travellers focusing on Buddhist heritage and a quieter base.']],
 Goa:[['Panaji','Hotels & boutique stays','₹1,500–₹7,000+','Central base for heritage, markets and North/South Goa drives.'],['Fontainhas','Heritage boutique stays','₹2,000–₹8,000+','Atmospheric old-quarter experience.'],['Calangute / Baga','Resorts & budget stays','₹1,500–₹8,000+','Convenient for beaches and nightlife.'],['Palolem / South Goa','Beach & resort stays','₹1,500–₹10,000+','Better for a quieter coastal holiday.']],
 Indore:[['MG Road / Central Indore','Hotels & mid-range','₹1,500–₹6,000','Good for Rajwada, markets and food trails.'],['Vijay Nagar','Modern & premium','₹2,000–₹8,000+','Restaurants, business facilities and modern hotels.'],['Palasia','Boutique & mid-range','₹1,500–₹6,000','Central lifestyle district.'],['Rau','Resort & highway stays','₹1,500–₹6,000','Useful for travellers exploring outside the core city.']],
 Guwahati:[['Paltan Bazaar','Budget & transit stays','₹1,000–₹4,500','Practical central base with transport connections.'],['Uzan Bazaar','Boutique & mid-range','₹1,500–₹6,000','Good for riverfront and central city experiences.'],['GS Road','Hotels & premium','₹2,000–₹8,000+','Modern hotels, shopping and restaurants.'],['Khanapara','Modern & business stays','₹1,500–₹6,000','Useful for longer stays and southern Guwahati.']],
 'New Delhi':[['Connaught Place','Hotels & premium','₹2,500–₹12,000+','Central base for major monuments, food and metro access.'],['Paharganj','Budget stays','₹700–₹4,000','Large range of budget accommodation near New Delhi station.'],['Karol Bagh','Budget to mid-range','₹1,000–₹5,000','Good value and shopping access.'],['South Delhi','Boutique & premium','₹2,500–₹12,000+','Quieter upscale neighbourhoods and good connectivity.']],
 Kurnool:[['Kurnool City Centre','Budget & mid-range','₹900–₹4,000','Practical base for city sights and local food.'],['Near Railway Station','Budget & transit stays','₹800–₹3,500','Convenient for short visits and onward travel.'],['NH44 corridor','Highway hotels','₹1,000–₹4,500','Useful for road trips and nearby attractions.'],['Orvakal side','Resort-style stays','₹1,500–₹5,000','Better for travellers combining rock landscapes with Kurnool.']],
 Tirupati:[['Tirupati City','Hotels & budget stays','₹1,000–₹5,000','Convenient for city temples and transport.'],['Tirumala approach','Pilgrim accommodation','₹500–₹3,000+','Useful for travellers focused on the Tirumala pilgrimage; availability can vary.'],['Alipiri area','Mid-range stays','₹1,500–₹6,000','Convenient for the hill route and city access.'],['Renigunta Road','Hotels & transit stays','₹1,200–₹5,000','Practical for railway/airport connections.']],
 Vijayawada:[['Benz Circle','Hotels & modern stays','₹1,500–₹6,000','Central commercial area with restaurants and transport.'],['MG Road','Business & mid-range','₹1,500–₹6,000','Convenient for city exploration.'],['Bhavanipuram','Budget & mid-range','₹1,000–₹4,500','Useful for riverfront and north-side access.'],['Kanaka Durga Temple area','Pilgrim & budget stays','₹800–₹4,000','Convenient for temple visits and short stays.']],
 Nagpur:[['Sitabuldi / Central Nagpur','Hotels & mid-range','₹1,200–₹5,500','Central for city sights and shopping.'],['Dharampeth','Boutique & lifestyle','₹1,800–₹6,500','Restaurants and quieter neighbourhood atmosphere.'],['Wardha Road','Business & premium','₹2,000–₹8,000+','Modern hotels and airport-side convenience.'],['Sadar','Budget to mid-range','₹1,200–₹5,000','Good mix of food, shopping and city access.']]
};

function accommodationCity(){return document.getElementById('citySelect')?.value||'';}
function staySearchUrl(city,area){return 'https://www.google.com/maps/search/hotels+in+'+encodeURIComponent(area+' '+city);}
function ensureAccommodation(){
 if(document.getElementById('accommodation')) return;
 const section=document.createElement('section'); section.className='section accommodation-section'; section.id='accommodation';
 section.innerHTML='<div class="heading"><div><p class="eyebrow">STAY SMART</p><h2>Where will you<br><em>stay in the city?</em></h2></div><p>Choose a neighbourhood based on your trip style. These are indicative stay categories and budget bands; live room prices and availability should be checked before booking.</p></div><div class="stay-toolbar"><div class="stay-city"><span>⌖</span><div><small>SELECTED DESTINATION</small><strong id="stayCityName">Choose a city</strong></div></div><div class="stay-filters"><button class="stay-filter active" data-filter="All">All</button><button class="stay-filter" data-filter="Budget">Budget</button><button class="stay-filter" data-filter="Mid-range">Mid-range</button><button class="stay-filter" data-filter="Premium">Premium</button></div></div><div class="stay-grid" id="stayGrid"><div class="stay-empty">Select a city to see accommodation areas.</div></div>';
 const planner=document.getElementById('planner'); planner.insertAdjacentElement('beforebegin',section);
 section.querySelectorAll('.stay-filter').forEach(b=>b.addEventListener('click',()=>{section.querySelectorAll('.stay-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderStays(b.dataset.filter)}));
}
function classifyStay(type){if(/Budget/i.test(type))return 'Budget';if(/premium/i.test(type))return 'Premium';return 'Mid-range';}
function renderStays(filter='All'){
 ensureAccommodation(); const city=accommodationCity(); const grid=document.getElementById('stayGrid'); document.getElementById('stayCityName').textContent=city||'Choose a city';
 if(!city){grid.innerHTML='<div class="stay-empty">⌖<strong>Select a city above</strong><span>Accommodation suggestions will appear here.</span></div>';return;}
 const rows=stayData[city]||[]; const shown=rows.filter(r=>filter==='All'||classifyStay(r[1])===filter);
 grid.innerHTML=shown.length?shown.map((r,i)=>{const category=classifyStay(r[1]);return `<article class="stay-card"><div class="stay-photo stay-photo-${i%4}"><span>${category.toUpperCase()}</span></div><div class="stay-body"><small class="stay-area">${r[0]}</small><h3>${r[1]}</h3><p>${r[3]}</p><div class="stay-meta"><b>${r[2]}</b><span>Indicative / night</span></div><a class="stay-map" href="${staySearchUrl(city,r[0])}" target="_blank" rel="noopener">Find stays in this area ↗</a></div></article>`}).join(''):'<div class="stay-empty">No stays match this filter for this city. Try All.</div>';
}
function bindAccommodation(){
 ensureAccommodation(); const select=document.getElementById('citySelect');
 if(select&&!select.dataset.stayBound){select.addEventListener('change',()=>setTimeout(()=>renderStays('All'),80));select.dataset.stayBound='1';}
 const old=window.setCity;
 if(old&&!old.__stayWrapped){const wrapped=function(city){old(city);setTimeout(()=>renderStays('All'),100)};wrapped.__stayWrapped=true;window.setCity=wrapped;}
 renderStays('All');
}
window.addEventListener('DOMContentLoaded',()=>setTimeout(bindAccommodation,350));
setTimeout(bindAccommodation,900);
