const data={Nature:[['Orvakal Rock Garden','Kurnool · 22 km',95,'Ancient rock formations and open landscapes for a quieter sunset experience.'],['Gandikota Backwaters','Kadapa · 110 km',92,'A dramatic riverside escape with wide-open views.'],['Mallela Theertham','Srisailam · 85 km',90,'A forest waterfall experience in the Nallamala landscape.']],Heritage:[['Yaganti Caves','Kurnool · 90 km',96,'A striking temple-and-cave landscape with local legends.'],['Adoni Fort Trails','Adoni · 50 km',91,'Layered fort ruins and hilltop views often skipped by mainstream itineraries.'],['Belum Caves','Kolimigundla · 95 km',94,'Long cave passages, chambers and unusual geological formations.']],Food:[['Kurnool Old Bazaar','Kurnool · City',93,'Local snacks, small eateries and everyday food culture.'],['Nandyal Street Bites','Nandyal · 75 km',89,'Regional flavors and small local vendors worth exploring.'],['Rayalaseema Kitchen Trail','Kurnool region',91,'A food-first route focused on regional specialties.']],Culture:[['Local Handloom Trail','Kurnool region',88,'Meet the craft story behind regional textiles and traditional making.'],['Rayalaseema Village Life','Near Kurnool',90,'Explore local traditions, agriculture and everyday culture respectfully.'],['Kondareddy Buruju Stories','Kurnool · City',86,'A compact heritage stop connected to Kurnool history.']],Adventure:[['Nallamala Explorer Route','Srisailam region',94,'A road-trip route through forest landscapes and viewpoints.'],['Gandikota Canyon Edge','Gandikota · 110 km',95,'Cliffside landscapes for sunrise and photography.'],['Ahobilam Trail','Nandyal district · 130 km',93,'Temple, forest and hill trails combined into an adventurous day out.']]};
let selected='Nature';
const icons={Nature:'🌿',Heritage:'🏛️',Food:'🍜',Culture:'🎭',Adventure:'🧗'};
function renderVibes(){document.getElementById('vibes').innerHTML=Object.keys(data).map(k=>`<button class="vibe ${k===selected?'active':''}" onclick="selectVibe('${k}')"><span>${icons[k]}</span><b>${k==='Food'?'Local Food':k}</b><small>${k==='Nature'?'Quiet escapes':k==='Heritage'?'Stories & ruins':k==='Food'?'Eat like a local':k==='Culture'?'Local life':'Road less known'}</small></button>`).join('')}
function renderPlaces(){document.getElementById('resultLabel').textContent=`${selected==='Food'?'Local Food':selected} picks`;document.getElementById('places').innerHTML=data[selected].map(p=>`<article class="place"><span class="tag">✦ ${p[2]}/100</span><small>${p[1]}</small><h3>${p[0]}</h3><p>${p[3]}</p></article>`).join('')}
function selectVibe(v){selected=v;renderVibes();renderPlaces()}
function discover(){const city=document.getElementById('heroCity').value.trim()||'Kurnool';document.getElementById('planCity').value=city;scrollToId('discover')}
function scrollToId(id){document.getElementById(id).scrollIntoView({behavior:'smooth'})}
function generatePlan(){const city=document.getElementById('planCity').value.trim()||'Kurnool';const days=document.getElementById('days').value;const style=document.getElementById('style').value;const budget=document.getElementById('budget').value;const out=document.getElementById('output');out.classList.add('show');out.innerHTML=`<h3>✦ Your UnseenGo plan for ${city}</h3><p>${days} · ${style} · ${budget}</p><div class="plan-grid"><div class="day"><b>DAY 01</b><p>Start with a high-score local discovery and a cultural stop.</p></div><div class="day"><b>DAY 02</b><p>Explore a nature or heritage gem with local food.</p></div><div class="day"><b>DAY 03</b><p>Finish with an under-discovered experience and sunset viewpoint.</p></div></div>`}
renderVibes();renderPlaces();