const cities={
'Hyderabad':{region:'South',Nature:[['Khajaguda Hills','Hyderabad · City',94,'Rocky trails, sunset views and a quieter side of the city.'],['Durgam Cheruvu Backwaters','Hyderabad · City',88,'A calm urban escape with walking paths and lake views.'],['Osman Sagar Lakeside','Hyderabad · 25 km',90,'Open water landscapes and relaxed evening views.']],Heritage:[['Paigah Tombs','Hyderabad · City',96,'Intricate architecture and a peaceful heritage atmosphere.'],['Qutb Shahi Tombs Trails','Hyderabad · City',91,'Historic pathways and lesser-explored corners around the tomb complex.'],['Taramati Baradari','Hyderabad · City',87,'Historic pavilion with stories from Hyderabad’s past.']],Food:[['Old City Irani Café Trail','Hyderabad · City',95,'Explore traditional tea, bakery culture and local breakfast spots.'],['Mallepally Food Walk','Hyderabad · City',91,'A local-focused route through everyday flavours.'],['Himayatnagar Snack Trail','Hyderabad · City',87,'Casual evening bites away from the headline tourist stops.']],Culture:[['Shilparamam Craft Corners','Hyderabad · City',89,'Handicrafts, folk traditions and regional art experiences.'],['Nizam-era Neighbourhood Walk','Hyderabad · City',93,'Discover architecture and stories embedded in old neighbourhoods.'],['Telangana Folk Arts Trail','Hyderabad · City',90,'A culture-first route focused on local performing traditions.']],Adventure:[['Ananthagiri Day Escape','Vikarabad · 80 km',94,'Forest roads, viewpoints and outdoor exploration.'],['Kondapochamma Reservoir','Siddipet · 55 km',88,'Open landscapes for a relaxed road trip.'],['Bhainsa Adventure Route','Telangana · regional',85,'An offbeat drive through rural landscapes.']]},
'Bengaluru':{region:'South',Nature:[['Turahalli Forest','Bengaluru · 15 km',94,'Rocky trails and open views close to the city.'],['Hesaraghatta Grasslands','Bengaluru · 30 km',93,'Wide-open landscapes and quiet sunrise experiences.'],['Avalabetta Hills','Chikkaballapur · 90 km',91,'A scenic hill escape with fewer crowds.']],Heritage:[['Devanahalli Fort Corners','Bengaluru · 40 km',92,'Historic fort walls and local stories beyond central Bengaluru.'],['Tipu Sultan Summer Palace','Bengaluru · City',88,'Indo-Islamic architecture with a quieter heritage feel.'],['Mayo Hall Heritage Walk','Bengaluru · City',84,'Colonial-era architecture around the central city.']],Food:[['VV Puram Food Street','Bengaluru · City',94,'Classic local snacks and evening street-food culture.'],['Malleswaram Tiffin Trail','Bengaluru · City',96,'Traditional South Indian breakfast and café culture.'],['Basavanagudi Local Bites','Bengaluru · City',91,'Neighbourhood food experiences away from chains.']],Culture:[['Indian Music Experience','Bengaluru · City',90,'Interactive exploration of India’s musical heritage.'],['Malleswaram Heritage Walk','Bengaluru · City',92,'Temples, old homes, markets and neighbourhood stories.'],['Karnataka Craft Trail','Bengaluru · City',87,'Discover regional craft traditions and makers.']],Adventure:[['Skandagiri Night Trek','Chikkaballapur · 60 km',95,'Popular with trekkers for its hilltop sunrise experience.'],['Savandurga','Bengaluru · 50 km',93,'A dramatic monolith and challenging outdoor escape.'],['Makalidurga Trail','Bengaluru · 60 km',90,'Hill trekking with reservoir and countryside views.']]},
'Chennai':{region:'South',Nature:[['Pulicat Lake Edge','Tamil Nadu · 55 km',94,'Wetland landscapes and birdwatching beyond the city.'],['Guindy Eco Trail','Chennai · City',86,'A green pocket offering a different side of Chennai.'],['Muttukadu Backwaters','Chennai · 35 km',89,'Quiet waters and an easy coastal escape.']],Heritage:[['DakshinaChitra','Muttukadu · 25 km',94,'Living heritage showcasing South Indian homes and crafts.'],['San Thome Heritage Quarter','Chennai · City',88,'Historic architecture and stories around the cathedral district.'],['Vivekananda House','Chennai · City',86,'A compact heritage stop with a strong cultural story.']],Food:[['Royapettah Food Trail','Chennai · City',94,'Local tiffin, snacks and everyday Chennai flavours.'],['Mylapore Filter Coffee Trail','Chennai · City',97,'Traditional coffee, breakfast and neighbourhood food culture.'],['George Town Snack Walk','Chennai · City',92,'Historic market lanes filled with local bites.']],Culture:[['Kalakshetra Arts Trail','Chennai · City',95,'Classical dance, music and South Indian artistic traditions.'],['Mylapore Temple Streets','Chennai · City',93,'Neighbourhood culture surrounding historic temples and markets.'],['Cholamandal Artists’ Village','Chennai · 9 km',91,'One of India’s important artist communities.']],Adventure:[['Mahabalipuram Coastal Ride','Tamil Nadu · 60 km',91,'A scenic road trip combining coast, heritage and open roads.'],['Covelong Surf Escape','Chennai · 40 km',94,'Surfing and coastal experiences away from city routines.'],['Pulicat Cycling Route','Tamil Nadu · 55 km',88,'An easy outdoor route around wetland landscapes.']]},
'Mumbai':{region:'West',Nature:[['Sanjay Gandhi National Park Trails','Mumbai · City',94,'Forest trails and biodiversity inside the metropolitan area.'],['Gorai Mangroves','Mumbai · 35 km',90,'A quieter coastal ecosystem away from central Mumbai.'],['Yeoor Hills','Thane · 35 km',92,'Green hill trails and a quick nature escape.']],Heritage:[['Khotachiwadi','Mumbai · City',95,'A historic village-like lane of old homes in the city.'],['Sewri Fort','Mumbai · City',89,'Compact fort ruins with a very different urban setting.'],['Bhau Daji Lad Museum','Mumbai · City',91,'Architecture, art and stories from Mumbai’s past.']],Food:[['Mohammed Ali Road Side Lanes','Mumbai · City',95,'A deep dive into Mumbai’s evening food culture.'],['Girgaon Breakfast Trail','Mumbai · City',92,'Local snacks and traditional breakfast spots.'],['Dadar Parsi Food Trail','Mumbai · City',90,'Neighbourhood food culture with historic influences.']],Culture:[['Kala Ghoda Art Walk','Mumbai · City',93,'Galleries, public art and historic streets.'],['Banganga Heritage Walk','Mumbai · City',96,'An ancient water tank and one of Mumbai’s quieter heritage pockets.'],['Dharavi Craft Trail','Mumbai · City',91,'A guided look at local enterprise and craftsmanship.']],Adventure:[['Karnala Fort Trek','Raigad · 55 km',95,'A forested fort trek close to Mumbai.'],['Matheran Trail Escape','Raigad · 80 km',94,'A vehicle-free hill station experience.'],['Kundalika Rafting Route','Kolad · 120 km',96,'White-water adventure for a full-day escape.']]},
'Pune':{region:'West',Nature:[['Vetal Tekdi Trails','Pune · City',93,'Hill trails and city views without leaving Pune.'],['Pashan Lake','Pune · City',88,'A relaxed birdwatching and walking spot.'],['Tamhini Ghat','Pune · 65 km',96,'Monsoon landscapes, waterfalls and winding roads.']],Heritage:[['Pataleshwar Cave Temple','Pune · City',91,'Rock-cut architecture hidden within the urban centre.'],['Shaniwar Wada Backstreets','Pune · City',88,'Historic lanes and stories around the old Peshwa capital.'],['Lal Mahal Heritage Stop','Pune · City',85,'A compact historic site connected with Maratha history.']],Food:[['FC Road Local Bites','Pune · City',89,'Student-friendly local food and snack culture.'],['Camp Irani Café Trail','Pune · City',94,'Old café culture and classic Pune flavours.'],['Sadashiv Peth Food Walk','Pune · City',95,'Traditional Maharashtrian snacks and neighbourhood eateries.']],Culture:[['Raja Dinkar Kelkar Museum','Pune · City',95,'A remarkable collection of Indian everyday art and objects.'],['Shaniwar Peth Heritage Walk','Pune · City',91,'Old neighbourhood architecture and cultural stories.'],['Pune Theatre Trail','Pune · City',87,'Local theatre, music and performing arts.']],Adventure:[['Rajgad Trek','Pune · 55 km',97,'Fort trekking with dramatic Sahyadri landscapes.'],['Sinhagad Sunrise Trail','Pune · 30 km',94,'A classic hill-fort escape with strong outdoor appeal.'],['Andharban Forest Trek','Pune · 70 km',96,'A dense forest trek with valley views.']]},
'Kolkata':{region:'East',Nature:[['East Kolkata Wetlands','Kolkata · City',96,'A unique wetland ecosystem on the edge of the metropolis.'],['Acharya Jagadish Chandra Bose Indian Botanic Garden','Howrah · 10 km',92,'Huge green spaces and botanical diversity.'],['Ballygunge Lakes','Kolkata · City',82,'Small urban green pockets for a slower city walk.']],Heritage:[['Kumartuli Artisan Lanes','Kolkata · City',97,'Walk through workshops where traditional clay idols are made.'],['Marble Palace Area','Kolkata · City',91,'Old architecture and a glimpse into Kolkata’s historic neighbourhoods.'],['Metcalfe Hall Quarter','Kolkata · City',87,'Colonial architecture around the riverfront district.']],Food:[['North Kolkata Mishti Trail','Kolkata · City',97,'Traditional sweets and neighbourhood food culture.'],['College Street Coffee Trail','Kolkata · City',94,'Bookshops, cafés and classic adda culture.'],['Tiretta Bazaar Breakfast','Kolkata · City',96,'A historic morning food experience with Chinese-Indian influences.']],Culture:[['Kumartuli Art Trail','Kolkata · City',98,'Living craft tradition and artisan workshops.'],['College Street Book Walk','Kolkata · City',95,'One of India’s richest literary neighbourhood experiences.'],['Jorasanko Cultural Quarter','Kolkata · City',94,'Literature, art and Bengal’s cultural history.']],Adventure:[['Sundarbans Edge Expedition','West Bengal · 100+ km',97,'Mangroves, waterways and wildlife-focused exploration.'],['Bakkhali Coastal Escape','West Bengal · 125 km',89,'A quieter beach destination for a road trip.'],['Mukutmanipur Weekend Route','West Bengal · 230 km',86,'Reservoir landscapes and a slower countryside escape.']]},
'Jaipur':{region:'North',Nature:[['Nahargarh Forest Trails','Jaipur · City',94,'Aravalli trails and sunset viewpoints beyond palace tourism.'],['Ramgarh Lake Region','Jaipur · 35 km',89,'A quieter landscape for an open-air escape.'],['Sambhar Lake Day Trip','Rajasthan · 70 km',95,'Vast salt-lake landscapes and birdlife.']],Heritage:[['Panna Meena ka Kund','Jaipur · City',96,'Geometric stepwell architecture in a quieter setting.'],['Gaitore Ki Chhatriyan','Jaipur · City',94,'Ornate royal cenotaphs away from the busiest sights.'],['Anokhi Museum of Hand Printing','Amer · 20 km',92,'Traditional textile printing and craft heritage.']],Food:[['Ramganj Food Walk','Jaipur · City',96,'Local snacks and street-food traditions.'],['Bapu Bazaar Snack Trail','Jaipur · City',90,'Traditional sweets, kachoris and local bites.'],['Old Jaipur Lassi Trail','Jaipur · City',88,'Classic drinks and neighbourhood food culture.']],Culture:[['Jawahar Kala Kendra','Jaipur · City',92,'Contemporary and traditional arts in one cultural campus.'],['Blue Pottery Craft Trail','Jaipur · City',95,'Meet the craft story behind Jaipur’s distinctive ceramics.'],['Kishanpole Woodwork Lane','Jaipur · City',91,'Traditional carving and artisan workshops.']],Adventure:[['Amer–Nahargarh Cycling Route','Jaipur · City',92,'An active way to see the Aravallis and old Jaipur.'],['Chokhi Dhani Rural Experience','Jaipur · 20 km',86,'Village-themed cultural experiences and performances.'],['Aravalli Hiking Route','Jaipur · Regional',91,'Offbeat hill walks around Jaipur’s rocky landscape.']]},
'Ahmedabad':{region:'West',Nature:[['Thol Lake','Ahmedabad · 40 km',95,'Wetland landscapes and birdwatching.'],['Nal Sarovar Edge','Gujarat · 65 km',97,'Large wetland landscapes with migratory bird experiences.'],['Riverfront Sunrise Trail','Ahmedabad · City',84,'A calm early-morning city walk.']],Heritage:[['Adalaj Stepwell','Gandhinagar · 20 km',98,'A spectacular stepwell with detailed stone architecture.'],['Sarkhej Roza','Ahmedabad · City',95,'Quiet Indo-Islamic architecture and historic courtyards.'],['Pol Houses Heritage Walk','Ahmedabad · City',97,'Traditional neighbourhood architecture and local stories.']],Food:[['Manek Chowk Night Trail','Ahmedabad · City',96,'A famous late-evening street-food experience.'],['Old Ahmedabad Breakfast Walk','Ahmedabad · City',94,'Local snacks and traditional Gujarati breakfast.'],['Law Garden Food Trail','Ahmedabad · City',91,'Casual evening street food and local favourites.']],Culture:[['Calico Museum Quarter','Ahmedabad · City',94,'Textiles, craft and design heritage.'],['Heritage Pol Walk','Ahmedabad · City',97,'Architecture, community spaces and old-city stories.'],['Kite Culture Trail','Ahmedabad · City',88,'Explore the city’s distinctive kite-making traditions.']],Adventure:[['Polo Forest Route','Gujarat · 160 km',96,'Forest, ruins and a rewarding road-trip combination.'],['Saputara Hills Escape','Gujarat · 400 km',90,'A longer hill-station adventure through Gujarat.'],['Ratan Mahal Wildlife Route','Gujarat · 180 km',88,'A nature-focused road trip into eastern Gujarat.']]},
'Lucknow':{region:'North',Nature:[['Kukrail Forest','Lucknow · City',91,'A green urban escape with forest trails.'],['Janeshwar Mishra Park Quiet Trails','Lucknow · City',84,'Large landscaped spaces for cycling and walking.'],['Chattar Manzil Riverfront Area','Lucknow · City',83,'A slower route through old Lucknow near the river.']],Heritage:[['Chota Imambara Lanes','Lucknow · City',95,'Ornate architecture and historic neighbourhood streets.'],['Husainabad Heritage Walk','Lucknow · City',97,'A dense cluster of monuments and old-city stories.'],['Dilkusha Kothi Ruins','Lucknow · City',94,'Atmospheric colonial-era ruins in a green setting.']],Food:[['Aminabad Kebab Trail','Lucknow · City',98,'Classic Awadhi street food and local favourites.'],['Chowk Tunday Trail','Lucknow · City',97,'A deep dive into Lucknow’s famous kebab culture.'],['Hazratganj Chaat Walk','Lucknow · City',92,'Traditional chaat and evening snacks.']],Culture:[['Chikankari Artisan Trail','Lucknow · City',98,'Discover the craft behind Lucknow’s iconic embroidery.'],['Kakori Cultural Route','Lucknow · 25 km',89,'Local food and heritage stories outside the centre.'],['Old Lucknow Poetry Walk','Lucknow · City',91,'Explore tehzeeb, literature and historic neighbourhoods.']],Adventure:[['Dudhwa Road Expedition','Uttar Pradesh · 220 km',96,'A wildlife-focused road trip into the Terai landscape.'],['Nawabganj Bird Sanctuary','Unnao · 45 km',92,'Birdwatching and wetland exploration.'],['Kukrail Cycling Route','Lucknow · City',87,'An easy outdoor route within the city.']]},
'Bhubaneswar':{region:'East',Nature:[['Deras Dam','Bhubaneswar · 25 km',94,'Forest, reservoir and quiet picnic landscapes.'],['Nandankanan Forest Trails','Bhubaneswar · 20 km',91,'Green landscapes around a major biodiversity area.'],['Dhauli Hills','Bhubaneswar · 10 km',90,'River views, hills and a peaceful setting.']],Heritage:[['Udayagiri & Khandagiri Caves','Bhubaneswar · City',97,'Ancient rock-cut caves and panoramic views.'],['Mukteshwar Temple Lanes','Bhubaneswar · City',94,'Intricate temple architecture beyond the main tourist circuit.'],['Rajarani Temple','Bhubaneswar · City',93,'Detailed sandstone architecture in a quiet garden setting.']],Food:[['Unit 1 Local Food Trail','Bhubaneswar · City',88,'Everyday Odia flavours and snacks.'],['Old Town Dahibara Trail','Bhubaneswar · City',96,'A local favourite for a classic Odia snack.'],['Sakhigopal Street Bites','Odisha · Regional',86,'Small-town food culture on a regional route.']],Culture:[['Odisha Handloom Trail','Bhubaneswar · City',94,'Explore traditional weaving and textiles.'],['Ekamra Heritage Walk','Bhubaneswar · City',96,'Temples, lanes and living heritage around old Bhubaneswar.'],['Odissi Dance Experience','Bhubaneswar · City',93,'Classical dance and Odisha’s cultural traditions.']],Adventure:[['Chandaka Forest Route','Bhubaneswar · 20 km',94,'Forest roads and wildlife-oriented exploration.'],['Daringbadi Hill Escape','Odisha · 250 km',91,'A scenic hill destination for a longer road trip.'],['Chilika Lagoon Expedition','Odisha · 100 km',97,'Boating, wetlands and birdwatching.']]},
'Kochi':{region:'South',Nature:[['Kumbalangi Village','Kochi · 15 km',96,'Backwaters, fishing traditions and village landscapes.'],['Mangalavanam Bird Sanctuary','Kochi · City',93,'A small mangrove ecosystem inside the city.'],['Kadamakudy Islands','Kochi · 20 km',97,'Quiet island roads, paddy fields and sunset views.']],Heritage:[['Mattancherry Backstreets','Kochi · City',96,'Historic lanes, old warehouses and multicultural heritage.'],['Poonithura Palace Area','Kochi · Regional',84,'A quieter look at Kerala’s architectural heritage.'],['Jew Town Craft Trail','Kochi · City',94,'Historic streets, antiques and cultural layers.']],Food:[['Fort Kochi Café Trail','Kochi · City',92,'Small cafés and coastal flavours in historic streets.'],['Kumbalangi Seafood Trail','Kochi · 15 km',96,'Local seafood and village-style cooking.'],['Broadway Market Food Walk','Kochi · City',94,'Everyday spices, snacks and market culture.']],Culture:[['Kathakali Experience','Kochi · City',97,'Traditional performance and Kerala cultural storytelling.'],['Kerala Folklore Museum','Kochi · City',94,'Architecture, objects and folk traditions.'],['Mattancherry Art Walk','Kochi · City',92,'Contemporary art within historic neighbourhoods.']],Adventure:[['Kadamakudy Cycling Route','Kochi · 20 km',96,'Flat island roads and scenic cycling.'],['Thattekad Birding Escape','Kerala · 60 km',95,'Forest and birdwatching-focused adventure.'],['Kumbalangi Kayak Route','Kochi · 15 km',97,'Explore backwaters from the water.']]},
'Varanasi':{region:'North',Nature:[['Assi Ghat Sunrise Walk','Varanasi · City',92,'A quieter start to the day along the river.'],['Rajghat River Edge','Varanasi · City',88,'A less-busy riverside atmosphere.'],['Sarnath Deer Park','Sarnath · 10 km',91,'Green space around an important Buddhist heritage area.']],Heritage:[['Sarnath Archaeological Area','Sarnath · 10 km',98,'Ancient Buddhist heritage beyond the busy riverfront.'],['Ramnagar Fort Lanes','Varanasi · 15 km',93,'Historic fort setting across the Ganga.'],['Old City Hidden Lanes','Varanasi · City',96,'Dense lanes filled with architecture, shrines and local stories.']],Food:[['Kachori Sabzi Morning Trail','Varanasi · City',97,'A classic local breakfast experience.'],['Banarasi Paan Walk','Varanasi · City',94,'Discover the city’s iconic paan culture.'],['Assi Street Food Trail','Varanasi · City',93,'Local snacks and evening food around Assi.']],Culture:[['Weaver Village Trail','Varanasi · Regional',97,'Explore Banarasi weaving and artisan traditions.'],['Classical Music Evening','Varanasi · City',95,'Experience the city’s deep musical heritage.'],['Sarnath Buddhist Culture Trail','Sarnath · 10 km',96,'Museums, monasteries and Buddhist traditions.']],Adventure:[['Ganga Dawn Boat Route','Varanasi · City',95,'A peaceful river experience at sunrise.'],['Chunar Fort Expedition','Mirzapur · 40 km',94,'Historic fort and river landscapes.'],['Vindhya Road Escape','Uttar Pradesh · Regional',87,'A countryside route beyond the city.']]},
'Goa':{region:'West',Nature:[['Chorla Forest Route','Goa · 60 km',96,'Waterfalls, forest roads and quieter landscapes.'],['Chorao Island','Goa · 20 km',95,'Mangroves, villages and birdwatching by ferry.'],['Butterfly Beach','South Goa · 45 km',94,'A small scenic beach reached away from the busiest routes.']],Heritage:[['Fontainhas Heritage Lanes','Panaji · City',96,'Colourful old homes and Portuguese-era streets.'],['Chandor Heritage Trail','South Goa · 35 km',94,'Historic houses and village heritage.'],['Old Goa Village Edges','Goa · Regional',88,'Quiet heritage corners outside the headline monuments.']],Food:[['Fontainhas Café Trail','Panaji · City',94,'Goan-Portuguese flavours and neighbourhood cafés.'],['Mapusa Market Food Walk','Goa · 15 km',96,'Local produce, snacks and everyday food culture.'],['South Goa Seafood Trail','Goa · Regional',98,'Traditional seafood and village-style cooking.']],Culture:[['Goan Folk Music Trail','Goa · Regional',91,'Local music traditions and community performances.'],['Latin Quarter Art Walk','Panaji · City',95,'Architecture, galleries and local creative culture.'],['Cashew Feni Heritage Route','Goa · Regional',89,'Traditional food and beverage-making culture.']],Adventure:[['Dudhsagar Expedition','Goa · Regional',98,'Waterfalls and forest landscapes for an adventurous day.'],['Netravali Wildlife Route','South Goa · 50 km',95,'Forest, waterfalls and rural roads.'],['Grande Island Snorkel Route','Goa · Coast',94,'Marine adventure away from crowded beaches.']]},
'Indore':{region:'Central',Nature:[['Ralamandal Wildlife Sanctuary','Indore · 15 km',94,'A quick forest escape close to the city.'],['Pipliyapala Lake','Indore · City',85,'A relaxed lake and evening walking route.'],['Janapav Hills','Indore · 45 km',93,'Hill landscapes and a road-trip escape.']],Heritage:[['Lal Bagh Palace','Indore · City',94,'Historic palace architecture and landscaped grounds.'],['Rajwada Backstreets','Indore · City',93,'Old-city architecture around the famous palace.'],['Kanch Mandir','Indore · City',89,'An intricate Jain temple with mirror work.']],Food:[['Sarafa Night Food Trail','Indore · City',99,'One of India’s strongest late-night street-food experiences.'],['Chappan Dukan Trail','Indore · City',96,'Popular local snacks and quick bites.'],['Poha-Jalebi Breakfast Route','Indore · City',98,'A quintessential local breakfast experience.']],Culture:[['Lal Bagh Heritage Walk','Indore · City',90,'Architecture and stories from Indore’s royal era.'],['Maratha-era Temple Trail','Indore · City',91,'Historic temples and neighbourhood culture.'],['Malwa Craft Trail','Madhya Pradesh · Regional',87,'Regional craft traditions and local makers.']],Adventure:[['Patalpani Waterfall Route','Indore · 35 km',95,'A scenic monsoon destination and short hike.'],['Mhow Forest Route','Indore · 25 km',89,'Green roads and weekend outdoor exploration.'],['Janapav Trek','Indore · 45 km',94,'Hill trekking and panoramic countryside views.']]},
'Guwahati':{region:'Northeast',Nature:[['Deepor Beel','Guwahati · City',97,'Wetland ecosystem and birdwatching.'],['Pobitora Wildlife Route','Assam · 50 km',96,'Grassland wildlife and countryside landscapes.'],['Umananda Island','Guwahati · River',92,'A small river island escape in the Brahmaputra.']],Heritage:[['Sualkuchi Silk Village','Assam · 35 km',97,'Traditional silk weaving and artisan culture.'],['Kamakhya Old Quarter','Guwahati · City',94,'Temple traditions and surrounding heritage lanes.'],['Assam State Museum Trail','Guwahati · City',88,'Regional history, archaeology and cultural objects.']],Food:[['Uzan Bazaar Food Trail','Guwahati · City',92,'Local Assamese meals and small eateries.'],['Fancy Bazaar Snack Walk','Guwahati · City',90,'Busy market lanes and regional snacks.'],['Assamese Thali Trail','Guwahati · City',96,'A food-first introduction to Assamese flavours.']],Culture:[['Sualkuchi Weaving Trail','Assam · 35 km',98,'Meet the makers behind Assam silk traditions.'],['Assamese Music Evening','Guwahati · City',90,'Local music and cultural performances.'],['Srimanta Sankardev Culture Route','Assam · Regional',95,'Explore Assam’s Vaishnavite cultural heritage.']],Adventure:[['Brahmaputra River Cruise','Guwahati · River',94,'A different perspective on the city and river.'],['Shillong Road Escape','Meghalaya · 100 km',96,'A scenic mountain road trip from Guwahati.'],['Haflong Hill Route','Assam · 330 km',89,'A longer hill-country adventure.']]},
'New Delhi':{region:'North',Nature:[['Sanjay Van','Delhi · City',94,'A large forest pocket with walking trails.'],['Asola Bhatti Wildlife Sanctuary','Delhi · South',96,'Rocky Aravalli landscapes and biodiversity.'],['Yamuna Biodiversity Park','Delhi · City',91,'Wetlands and native habitats in the capital.']],Heritage:[['Mehrauli Archaeological Park','Delhi · City',98,'Ruins, stepwells and monuments spread across a green landscape.'],['Nizamuddin Heritage Quarter','Delhi · City',96,'Historic lanes, tombs and living culture.'],['Sultan Garhi Tomb','Delhi · City',91,'An atmospheric early Indo-Islamic monument.']],Food:[['Old Delhi Breakfast Trail','Delhi · City',98,'Classic parathas, kebabs and morning street food.'],['Nizamuddin Food Walk','Delhi · City',97,'A rich mix of Mughlai and local flavours.'],['Majnu ka Tila Café Trail','Delhi · City',91,'Tibetan and contemporary food culture.']],Culture:[['Lodhi Art District','Delhi · City',95,'Public art, galleries and creative neighbourhood culture.'],['Kathputli Colony Craft Story','Delhi · City',90,'Traditional puppetry and artisan traditions.'],['Dilli Haat Craft Trail','Delhi · City',94,'Handicrafts and food traditions from across India.']],Adventure:[['Aravalli Cycling Route','Delhi · South',93,'An active route through Delhi’s rocky green belt.'],['Damdama Lake Escape','Haryana · 45 km',91,'Rocky hills, water and outdoor activities.'],['Sohna Hills Route','Haryana · 55 km',88,'A short road trip into the Aravallis.']]},
'Kurnool':{region:'South',Nature:[['Orvakal Rock Garden','Kurnool · 22 km',95,'Ancient rock formations and open landscapes for a quieter sunset experience.'],['Gandikota Backwaters','Kadapa · 110 km',92,'A dramatic riverside escape with wide-open views.'],['Mallela Theertham','Srisailam · 85 km',90,'A forest waterfall experience in the Nallamala landscape.']],Heritage:[['Yaganti Caves','Kurnool · 90 km',96,'A striking temple-and-cave landscape with local legends.'],['Adoni Fort Trails','Adoni · 50 km',91,'Layered fort ruins and hilltop views often skipped by mainstream itineraries.'],['Belum Caves','Kolimigundla · 95 km',94,'Long cave passages, chambers and unusual geological formations.']],Food:[['Kurnool Old Bazaar','Kurnool · City',93,'Local snacks, small eateries and everyday food culture.'],['Nandyal Street Bites','Nandyal · 75 km',89,'Regional flavours and small local vendors.'],['Rayalaseema Kitchen Trail','Kurnool region',91,'A food-first route focused on regional specialties.']],Culture:[['Local Handloom Trail','Kurnool region',88,'Meet the craft story behind regional textiles and traditional making.'],['Rayalaseema Village Life','Near Kurnool',90,'Explore local traditions, agriculture and everyday culture respectfully.'],['Kondareddy Buruju Stories','Kurnool · City',86,'A compact heritage stop connected to Kurnool history.']],Adventure:[['Nallamala Explorer Route','Srisailam region',94,'A road-trip route through forest landscapes and viewpoints.'],['Gandikota Canyon Edge','Gandikota · 110 km',95,'Cliffside landscapes for sunrise and photography.'],['Ahobilam Trail','Nandyal district · 130 km',93,'Temple, forest and hill trails combined into an adventurous day out.']]},
'Tirupati':{region:'South',Nature:[['Talakona Forest','Chittoor · 50 km',96,'Forest trails and one of the region’s best-known waterfalls.'],['Kapila Theertham Trails','Tirupati · City',88,'A green hill-side escape close to the city.'],['Horsley Hills Route','Andhra Pradesh · 130 km',92,'Cooler hill landscapes and a scenic road trip.']],Heritage:[['Chandragiri Fort','Tirupati · 15 km',95,'Historic fort complex with hilltop views.'],['Sri Kalahasti Old Streets','Tirupati region · 40 km',91,'Temple-town heritage and local lanes.'],['Gudi Mallam Heritage Stop','Chittoor · Regional',89,'An ancient temple site with a distinctive history.']],Food:[['Tirupati Breakfast Trail','Tirupati · City',90,'Local breakfast and Andhra vegetarian food.'],['Rayalaseema Meals Trail','Tirupati · City',94,'Regional flavours with spicy Andhra cuisine.'],['Temple-town Snack Walk','Tirupati · City',88,'Local sweets and snacks around the old town.']],Culture:[['Kalamkari Craft Trail','Tirupati region',96,'Explore the traditional painted-textile craft of the region.'],['Chandragiri Cultural Route','Tirupati · 15 km',91,'Fort history and local heritage.'],['Andhra Classical Arts Trail','Tirupati · Regional',88,'Music, dance and temple-linked traditions.']],Adventure:[['Talakona Trek','Chittoor · 50 km',97,'Forest trekking and waterfall landscapes.'],['Horsley Hills Cycling Route','Andhra Pradesh · 130 km',91,'Hill roads and viewpoints for an active escape.'],['Seshachalam Hills Route','Tirupati · Regional',94,'Forest roads and biodiversity-focused exploration.']]},
'Vijayawada':{region:'South',Nature:[['Kondapalli Forest','Vijayawada · 25 km',94,'Hill forests and a quieter outdoor escape.'],['Bhavani Island','Vijayawada · City',91,'River-island recreation away from the urban core.'],['Krishna River Sunrise Route','Vijayawada · City',88,'Open river views and an easy morning experience.']],Heritage:[['Kondapalli Fort','Vijayawada · 25 km',96,'Hilltop fort ruins with wide regional views.'],['Undavalli Caves','Vijayawada · 8 km',97,'Rock-cut architecture overlooking the Krishna landscape.'],['Amaravati Heritage Route','Amaravati · 35 km',95,'Buddhist heritage and archaeological stories.']],Food:[['Vijayawada Street Bites','Vijayawada · City',93,'Local Andhra snacks and spicy favourites.'],['Guntur Chilli Food Trail','Guntur · 35 km',94,'Explore the region’s bold chilli-forward cuisine.'],['Krishna Delta Meals Route','Andhra Pradesh · Regional',90,'Traditional meals and agricultural-region flavours.']],Culture:[['Kondapalli Toy Makers','Vijayawada · 25 km',97,'Traditional painted wooden toys and artisan stories.'],['Amaravati Buddhist Culture Trail','Amaravati · 35 km',95,'Art, archaeology and Buddhist heritage.'],['Kuchipudi Village Experience','Krishna district · 60 km',98,'Explore the roots of the classical Kuchipudi dance tradition.']],Adventure:[['Kondapalli Trek','Vijayawada · 25 km',93,'Hill walking and fort exploration.'],['Krishna River Kayak Route','Vijayawada · Regional',89,'Water-based exploration with open river landscapes.'],['Mangalagiri Hill Route','Guntur · 20 km',90,'A short hill escape with cultural and outdoor elements.']]},
'Nagpur':{region:'Central',Nature:[['Pench Gateway Route','Maharashtra · 100 km',97,'Wildlife-focused road trip near the city.'],['Ambazari Lake Trails','Nagpur · City',86,'A relaxed urban nature walk.'],['Umred Karhandla Wildlife Route','Nagpur · 60 km',96,'Forest and wildlife exploration.']],Heritage:[['Deekshabhoomi Cultural Stop','Nagpur · City',92,'An important cultural and architectural landmark.'],['Gondwana Heritage Route','Vidarbha · Regional',89,'Explore regional history and tribal heritage.'],['Sitabuldi Fort Area','Nagpur · City',87,'Historic fort setting in the middle of the city.']],Food:[['Tarri Poha Breakfast Trail','Nagpur · City',97,'A distinctive local breakfast experience.'],['Saoji Food Trail','Nagpur · City',99,'Explore Nagpur’s famous spicy Saoji cuisine.'],['Itwari Market Bites','Nagpur · City',92,'Market lanes and local snacks.']],Culture:[['Gond Tribal Art Trail','Vidarbha · Regional',93,'Regional craft and tribal art traditions.'],['Nagpur Heritage Walk','Nagpur · City',88,'Old markets, architecture and city stories.'],['Orange Culture Trail','Nagpur · Regional',85,'Explore the region’s agricultural identity.']],Adventure:[['Tadoba Expedition','Maharashtra · 150 km',98,'A major wildlife road-trip destination.'],['Pench Forest Route','Madhya Pradesh · 130 km',97,'Forest landscapes and wildlife experiences.'],['Ramtek Hill Route','Nagpur · 50 km',91,'Hills, temple heritage and countryside views.']]}
};

const icons={Nature:'🌿',Heritage:'🏛️',Food:'🍜',Culture:'🎭',Adventure:'🧗'};
let selected='Nature';
let selectedCity='';

function cityNames(){return Object.keys(cities).sort();}
function populateCities(){
 const names=cityNames();
 const datalist=document.getElementById('cities');
 const select=document.getElementById('citySelect');
 const plan=document.getElementById('planCity');
 datalist.innerHTML=names.map(c=>`<option value="${c}"></option>`).join('');
 select.innerHTML='<option value="">Choose a city...</option>'+names.map(c=>`<option value="${c}">${c} · ${cities[c].region} India</option>`).join('');
 plan.innerHTML='<option value="">Choose a city...</option>'+names.map(c=>`<option value="${c}">${c}</option>`).join('');
 document.getElementById('cityChips').innerHTML=names.map(c=>`<button class="city-chip" onclick="setCity('${c}')">${c}</button>`).join('');
}
function renderVibes(){
 document.getElementById('vibes').innerHTML=Object.keys(icons).map(k=>`<button class="vibe ${k===selected?'active':''}" onclick="selectVibe('${k}')"><span>${icons[k]}</span><b>${k==='Food'?'Local Food':k}</b><small>${k==='Nature'?'Quiet escapes':k==='Heritage'?'Stories & ruins':k==='Food'?'Eat like a local':k==='Culture'?'Local life':'Road less known'}</small></button>`).join('');
}
function renderPlaces(){
 const places=document.getElementById('places');
 if(!selectedCity){document.getElementById('resultLabel').textContent='Choose a city to see hidden gems';places.innerHTML='<div class="empty-state">⌖<strong>Your India journey starts here</strong><span>Select a city above to reveal its hidden gems.</span></div>';return;}
 const list=cities[selectedCity][selected]||[];
 document.getElementById('resultLabel').textContent=`${selected==='Food'?'Local Food':selected} picks · ${selectedCity}`;
 places.innerHTML=list.map((p,i)=>`<article class="place place-${i+1}"><span class="tag">✦ ${p[2]}/100</span><small>${p[1]}</small><h3>${p[0]}</h3><p>${p[3]}</p><span class="explore">Explore gem →</span></article>`).join('');
}
function selectVibe(v){selected=v;renderVibes();renderPlaces();}
function setCity(city){
 if(!cities[city])return;
 selectedCity=city;
 document.getElementById('heroCity').value=city;
 document.getElementById('citySelect').value=city;
 document.getElementById('planCity').value=city;
 document.querySelectorAll('.city-chip').forEach(b=>b.classList.toggle('active',b.textContent.trim()===city));
 renderPlaces();
 document.dispatchEvent(new CustomEvent('unseengo:citychange',{detail:{city}}));
 document.getElementById('discover').scrollIntoView({behavior:'smooth',block:'start'});
}
function bindCitySelection(){
 const select=document.getElementById('citySelect');
 if(select&&!select.dataset.bound){
  select.addEventListener('change',e=>{if(e.target.value)setCity(e.target.value);});
  select.dataset.bound='1';
 }
 const hero=document.getElementById('heroCity');
 if(hero&&!hero.dataset.bound){
  hero.addEventListener('change',e=>{if(cities[e.target.value.trim()])setCity(e.target.value.trim());});
  hero.dataset.bound='1';
 }
}
function discover(){
 const city=document.getElementById('heroCity').value.trim();
 if(cities[city]){setCity(city);return;}
 if(!selectedCity){document.getElementById('discover').scrollIntoView({behavior:'smooth'});return;}
 renderPlaces();
}
function scrollToId(id){document.getElementById(id).scrollIntoView({behavior:'smooth'});}
function generatePlan(){
 const city=document.getElementById('planCity').value;
 if(!city){alert('Please choose a destination city first.');return;}
 const days=document.getElementById('days').value,style=document.getElementById('style').value,budget=document.getElementById('budget').value;
 const picks=cities[city][selected]||cities[city].Nature;
 const out=document.getElementById('output');out.classList.add('show');
 out.innerHTML=`<h3>✦ Your UnseenGo plan for ${city}</h3><p>${days} · ${style} · ${budget}</p><div class="plan-grid"><div class="day"><b>DAY 01</b><p>${picks[0][0]}<br>${picks[0][3]}</p></div><div class="day"><b>DAY 02</b><p>${picks[1][0]}<br>${picks[1][3]}</p></div><div class="day"><b>DAY 03</b><p>${picks[2][0]}<br>${picks[2][3]}</p></div></div>`;
}
populateCities();renderVibes();renderPlaces();bindCitySelection();
setTimeout(bindCitySelection,500);
