/* UnseenGo AI — dedicated city page for every supported destination */
(function(){
 const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const params=new URLSearchParams(location.search), city=params.get('city')||'', wikiCache={}, galleryCache={};
 const cityData=typeof cities!=='undefined'?cities[city]:null;
 const mapUrl=(name,placeCity)=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(name+' '+placeCity);
 const mapEmbed=(name,placeCity)=>'https://www.google.com/maps?q='+encodeURIComponent(name+' '+placeCity)+'&output=embed';
 const photoFunctionUrl='https://jpqbvliaaucyqnhcclbz.supabase.co/functions/v1/google-place-photos';
 function allPlaces(){const out=[],seen=new Set();if(cityData)Object.keys(cityData).forEach(cat=>{if(cat==='region'||!Array.isArray(cityData[cat]))return;cityData[cat].forEach(r=>{if(!r?.[0]||seen.has(r[0]))return;seen.add(r[0]);out.push({name:r[0],location:r[1]||city,score:r[2],description:r[3]||'',category:cat,famous:false});});});const famous=typeof famousPlaces!=='undefined'?(famousPlaces[city]||[]):[];famous.forEach(name=>{if(seen.has(name))return;seen.add(name);out.push({name,location:city,score:null,description:'A well-known landmark or attraction in '+city+'.',category:'Famous Landmark',famous:true});});return out;}
 function history(){return typeof cityStoryFallback!=='undefined'&&cityStoryFallback[city]?cityStoryFallback[city]:'Explore the architecture, communities, landscapes and traditions that shaped this destination.';}
 async function wiki(name){if(wikiCache[name])return wikiCache[name];try{const r=await fetch('https://en.wikipedia.org/api/rest_v1/page/summary/'+encodeURIComponent(name.replace(/ /g,'_')),{headers:{Accept:'application/json'}});if(!r.ok)throw 0;const d=await r.json(),x={text:d.extract||'',image:d.thumbnail?.source||'',description:d.description||''};wikiCache[name]=x;return x;}catch(e){const x={text:'',image:'',description:''};wikiCache[name]=x;return x;}}
 async function googlePhotoGallery(name,placeCity){try{const r=await fetch(photoFunctionUrl,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({place:name,city:placeCity})});if(!r.ok)return null;const d=await r.json();if(!Array.isArray(d.photos))return null;return {photos:d.photos.map(x=>({url:x.url,title:name,credit:x.attributions?.map(a=>a.displayName||a.uri).filter(Boolean).join(', ')||'Google Maps'})),place:d.place||null};}catch(e){return null;}}
 async function wikimediaGallery(name,placeCity){const key=name+'|'+placeCity;if(galleryCache[key])return galleryCache[key];const queries=[name+' '+placeCity,name];try{for(const query of queries){const url='https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch='+encodeURIComponent(query)+'&gsrnamespace=6&gsrlimit=12&prop=imageinfo&iiprop=url|extmetadata&iiurlwidth=1000&format=json&origin=*';const r=await fetch(url);if(!r.ok)continue;const d=await r.json(),pages=Object.values(d.query?.pages||{});const imgs=pages.map(p=>{const i=p.imageinfo?.[0],m=i?.extmetadata||{};return {url:i?.thumburl||i?.url||'',title:p.title?.replace(/^File:/,'')||name,credit:m.Credit?.value||m.Artist?.value||'Wikimedia Commons'};}).filter(x=>x.url);if(imgs.length){galleryCache[key]=imgs;return imgs;}}}catch(e){}galleryCache[key]=[];return [];}
 async function photoGallery(name,placeCity){const key=name+'|'+placeCity;if(galleryCache['google:'+key])return galleryCache['google:'+key];const google=await googlePhotoGallery(name,placeCity);if(google?.photos?.length){galleryCache['google:'+key]=google.photos;return google.photos;}const fallback=await wikimediaGallery(name,placeCity);galleryCache['google:'+key]=fallback;return fallback;}
 function renderHeader(){document.title=city+' — UnseenGo AI';document.getElementById('cityName').textContent=city||'Explore India';document.getElementById('cityRegion').textContent=cityData?.region?cityData.region+' India':'India';document.getElementById('cityHistory').textContent=history();const places=allPlaces();document.getElementById('placeCount').textContent=places.length;document.getElementById('categoryCount').textContent=new Set(places.map(p=>p.category)).size;document.getElementById('cityIntro').textContent=city?`Explore ${places.length} curated places across history, forts, nature, culture, food, adventure and famous landmarks.`:'Choose a destination from the homepage.';}
 function card(p,i){return `<article class="city-place-card" data-index="${i}" data-category="${esc(p.category)}" data-name="${esc(p.name).toLowerCase()}"><div class="place-image" id="img-${i}"><div class="image-loader">✦<span>Loading photo…</span></div></div><div class="place-card-body"><div class="place-top"><span>${esc(p.famous?'FAMOUS':'CURATED')}</span>${p.score?`<b>✦ ${esc(p.score)}</b>`:''}</div><small class="place-category">${esc(p.category)}</small><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><div class="place-location">⌖ ${esc(p.location||city)}</div><button class="details-button" data-open="${i}">View history, photos & map →</button></div></article>`;}
 function renderPlaces(){const places=allPlaces(),grid=document.getElementById('cityPlaces');grid.innerHTML=places.map(card).join('');document.querySelectorAll('.details-button').forEach(b=>b.addEventListener('click',()=>openPlace(Number(b.dataset.open))));document.querySelectorAll('.city-place-card').forEach(c=>c.addEventListener('click',e=>{if(e.target.closest('button'))return;openPlace(Number(c.dataset.index));}));places.forEach((p,i)=>loadImage(p,i));renderFilters(places);}
 async function loadImage(p,i){const el=document.getElementById('img-'+i);if(!el)return;const [imgs,d]=await Promise.all([photoGallery(p.name,p.location||city),wiki(p.name)]);if(!document.getElementById('img-'+i))return;const image=imgs[0]?.url||d.image||'';el.innerHTML=image?`<img src="${esc(image)}" alt="${esc(p.name)}" loading="lazy" onerror="this.parentElement.innerHTML='<div class=\'image-fallback\'>✦<span>Photo unavailable</span></div>'">`:'<div class="image-fallback">✦<span>Photo unavailable</span></div>';} 
 function renderFilters(places){const cats=['All',...new Set(places.map(p=>p.category))];document.getElementById('categoryFilters').innerHTML=cats.map((c,i)=>`<button class="filter-btn ${i===0?'active':''}" data-filter="${esc(c)}">${esc(c)}</button>`).join('');document.querySelectorAll('.filter-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');applyFilter(b.dataset.filter);}));}
 function applyFilter(filter){document.querySelectorAll('.city-place-card').forEach(c=>c.hidden=filter!=='All'&&c.dataset.category!==filter);}
 async function openPlace(i){const p=allPlaces()[i];if(!p)return;const modal=document.getElementById('placeModal');modal.classList.add('open');document.getElementById('modalTitle').textContent=p.name;document.getElementById('modalCategory').textContent=p.famous?'FAMOUS LANDMARK':p.category.toUpperCase();document.getElementById('modalLocation').textContent=p.location||city;document.getElementById('modalSummary').textContent=p.description;document.getElementById('modalMap').src=mapEmbed(p.name,p.location||city);document.getElementById('modalMapLink').href=mapUrl(p.name,p.location||city);document.getElementById('modalHistory').textContent='Loading the historical story…';document.getElementById('modalPhoto').innerHTML='<div class="modal-photo-loading">Loading featured photo…</div>';document.getElementById('modalGallery').innerHTML='';document.getElementById('photoCredit').textContent='';const [d,imgs]=await Promise.all([wiki(p.name),photoGallery(p.name,p.location||city)]);document.getElementById('modalHistory').textContent=d.text||'A dedicated historical summary was not found for this exact place. The curated description is shown above.';const gallery=imgs.length?imgs:(d.image?[{url:d.image,title:p.name,credit:'Wikipedia'}]:[]);document.getElementById('modalPhoto').innerHTML=gallery[0]?`<img src="${esc(gallery[0].url)}" alt="${esc(p.name)}" loading="lazy">`:'<div class="modal-photo-loading">Photo not available for this exact place.</div>';if(gallery.length>1){document.getElementById('modalGallery').innerHTML=gallery.slice(1,7).map(x=>`<figure><img src="${esc(x.url)}" alt="${esc(x.title)}" loading="lazy"></figure>`).join('');}if(gallery.length)document.getElementById('photoCredit').textContent='Photos may be supplied by Google Maps or Wikimedia Commons; attribution is shown where provided.';}
 function renderStays(){const grid=document.getElementById('cityStays'),rows=typeof stayData!=='undefined'?(stayData[city]||[]):[];grid.innerHTML=rows.length?rows.map(r=>`<article class="city-stay"><span>${esc(r[1])}</span><h3>${esc(r[0])}</h3><b>${esc(r[2])}</b><p>${esc(r[3])}</p><a target="_blank" rel="noopener" href="https://www.google.com/maps/search/hotels+in+${encodeURIComponent(r[0]+' '+city)}">Find stays nearby ↗</a></article>`).join(''):'<div class="city-empty">Accommodation areas for this destination are being added.</div>';}
 function close(){document.getElementById('placeModal').classList.remove('open');document.getElementById('modalMap').src='about:blank';}
 function init(){if(!cityData&&!(typeof famousPlaces!=='undefined'&&famousPlaces[city])){document.getElementById('cityName').textContent='City not found';document.getElementById('cityIntro').textContent='Return to Explore India and choose a supported destination.';return;}renderHeader();renderPlaces();renderStays();document.getElementById('placeSearch').addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('.city-place-card').forEach(c=>c.hidden=!!q&&!c.dataset.name.includes(q));});document.getElementById('modalClose').addEventListener('click',close);document.getElementById('modalBackdrop').addEventListener('click',close);document.addEventListener('keydown',e=>{if(e.key==='Escape')close();});}
 window.addEventListener('DOMContentLoaded',init);
})();