/* UnseenGo AI — stable city page controller + resilient place photos + live Supabase enrichment */
(function(){
'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const params=new URLSearchParams(location.search),city=params.get('city')||'';
const cityData=typeof cities!=='undefined'?cities[city]:null;
let placesCache=[];
const modal=()=>document.getElementById('placeModal');
const maps=(name,c)=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(name+' '+c);
const embed=(name,c)=>'https://www.google.com/maps?q='+encodeURIComponent(name+' '+c)+'&output=embed';
const PHOTO_ENDPOINT='https://jpqbvliaaucyqnhcclbz.supabase.co/functions/v1/google-place-photos';
const DATA_ENDPOINT='https://jpqbvliaaucyqnhcclbz.supabase.co/functions/v1/city-data';
const PUBLIC_KEY='sb_publishable_K-0R9a2lSginTIfxHk-cxQ_joorBonp';
const photoCache=new Map();
function cleanPage(){const m=modal();if(m){m.classList.remove('open');m.style.display='none';m.style.pointerEvents='none'}document.body.classList.remove('modal-open');document.body.style.removeProperty('overflow');document.body.style.removeProperty('position');document.body.style.removeProperty('top');document.body.style.removeProperty('left');document.body.style.removeProperty('right');document.body.style.removeProperty('width');document.body.style.removeProperty('cursor');document.documentElement.style.removeProperty('overflow');}
function fallback(){const out=[],seen=new Set();if(cityData)Object.keys(cityData).forEach(cat=>{if(cat==='region'||!Array.isArray(cityData[cat]))return;(cityData[cat]||[]).forEach(r=>{if(!r?.[0]||seen.has(r[0]))return;seen.add(r[0]);out.push({name:r[0],location:r[1]||city,score:r[2],description:r[3]||'',history:'',category:cat,famous:false,image_url:'',maps_url:''})})});const famous=typeof famousPlaces!=='undefined'?(famousPlaces[city]||[]):[];famous.forEach(name=>{if(seen.has(name))return;seen.add(name);out.push({name,location:city,score:null,description:'A well-known landmark or attraction in '+city+'.',history:'',category:'Famous Landmark',famous:true,image_url:'',maps_url:''})});return out;}
async function enrichCity(){try{const r=await fetch(DATA_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','apikey':PUBLIC_KEY},body:JSON.stringify({city,state:window.CITY_STATE?.[city]||''})});if(!r.ok)return null;return await r.json()}catch(e){return null}}
async function loadPlaces(){try{if(window.UnseenGoData?.loadPlaces){let rows=await window.UnseenGoData.loadPlaces(city);if(Array.isArray(rows)&&rows.length)return rows;await enrichCity();rows=await window.UnseenGoData.loadPlaces(city);if(Array.isArray(rows)&&rows.length)return rows}}catch(e){}return fallback()}
async function googlePhotos(name,c){try{const r=await fetch(PHOTO_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({place:name,city:c})});if(!r.ok)return [];const d=await r.json();return Array.isArray(d.photos)?d.photos.filter(x=>x&&x.url):[]}catch(e){return []}}
async function commonsPhotos(name,c){const queries=[name+' '+c,name];for(const q of queries){try{const u='https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch='+encodeURIComponent(q)+'&gsrnamespace=6&gsrlimit=8&prop=imageinfo&iiprop=url|extmetadata&iiurlwidth=1200&format=json&origin=*';const r=await fetch(u);if(!r.ok)continue;const d=await r.json();const pages=d.query?.pages?Object.values(d.query.pages):[];const imgs=pages.map(p=>p.imageinfo?.[0]).filter(Boolean).map(x=>({url:x.thumburl||x.url,source:'Wikimedia Commons'})).filter(x=>x.url);if(imgs.length)return imgs}catch(e){}}return []}
async function placePhotos(p){const key=(p.name||'')+'|'+(p.location||city);if(photoCache.has(key))return photoCache.get(key);let imgs=[];if(p.image_url)imgs=[{url:p.image_url,source:'Provided place image'}];if(!imgs.length)imgs=await googlePhotos(p.name,p.location||city);if(!imgs.length)imgs=await commonsPhotos(p.name,p.location||city);if(!imgs.length){try{const r=await fetch('https://en.wikipedia.org/api/rest_v1/page/summary/'+encodeURIComponent(p.name.replace(/ /g,'_')));const d=await r.json();if(d.thumbnail?.source)imgs=[{url:d.thumbnail.source,source:'Wikipedia'}]}catch(e){}}photoCache.set(key,imgs);return imgs}
function card(p,i){return `<article class="city-place-card" tabindex="0" role="button" data-index="${i}" data-category="${esc(p.category)}" data-name="${esc(p.name.toLowerCase())}"><div class="place-image" id="img-${i}"><div class="image-loader">✦<span>Loading photo…</span></div></div><div class="place-card-body"><div class="place-top"><span>${p.famous?'FAMOUS':'CURATED'}</span>${p.verification_status?`<b>✓ ${esc(p.verification_status)}</b>`:p.score?`<b>✦ ${esc(p.score)}</b>`:''}</div><small class="place-category">${esc(p.category)}</small><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><div class="place-location">⌖ ${esc(p.location||city)}</div><div class="card-action-hint">Click anywhere to explore complete details <span>→</span></div></div></article>`}
async function render(){const grid=document.getElementById('cityPlaces');grid.innerHTML=placesCache.map(card).join('');document.querySelectorAll('.city-place-card').forEach(el=>{const open=e=>{if(e.target.closest('a,button,input'))return;openPlace(Number(el.dataset.index))};el.addEventListener('click',open);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(e)}})});placesCache.forEach(async(p,i)=>{const imgs=await placePhotos(p);const box=document.getElementById('img-'+i);if(!box)return;if(imgs[0]?.url){box.innerHTML=`<img src="${esc(imgs[0].url)}" alt="${esc(p.name)}" loading="lazy" onerror="this.parentElement.innerHTML='<div class=\'image-fallback\'>✦<span>Photo unavailable</span></div>'">`;box.classList.add('google-photo');box.title=imgs[0].source||'Place photo'}else box.innerHTML='<div class="image-fallback">✦<span>Photo unavailable</span></div>'});const cats=['All',...new Set(placesCache.map(p=>p.category))];document.getElementById('categoryFilters').innerHTML=cats.map((c,i)=>`<button type="button" class="filter-btn ${i?'':'active'}" data-filter="${esc(c)}">${esc(c)}</button>`).join('');document.querySelectorAll('.filter-btn').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();document.querySelectorAll('.filter-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.city-place-card').forEach(c=>c.hidden=b.dataset.filter!=='All'&&c.dataset.category!==b.dataset.filter)}))}
function transport(p){const dest=p.name+' '+(p.location||city),origin=document.getElementById('transportOrigin'),direction=document.getElementById('directionLink'),pickup=document.getElementById('pickupLink');document.getElementById('transportDestination').textContent=p.name;function update(){const m=document.querySelector('.transport-mode.active')?.dataset.mode||'driving';const tm=['bus','train','metro'].includes(m)?'transit':m==='flight'?'driving':m;direction.href='https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(dest)+(origin.value?'&origin='+encodeURIComponent(origin.value):'')+'&travelmode='+tm;pickup.href='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent('transport pickup near '+dest)}document.querySelectorAll('.transport-mode').forEach(b=>{b.onclick=e=>{e.stopPropagation();document.querySelectorAll('.transport-mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');update()}});origin.oninput=update;document.getElementById('useLocation').onclick=e=>{e.stopPropagation();if(navigator.geolocation)navigator.geolocation.getCurrentPosition(pos=>{origin.value=pos.coords.latitude+','+pos.coords.longitude;update()});};update()}
async function openPlace(i){const p=placesCache[i],m=modal();if(!p||!m)return;m.style.display='block';m.style.pointerEvents='auto';m.classList.add('open');document.body.classList.remove('modal-open');document.body.style.removeProperty('overflow');document.documentElement.style.removeProperty('overflow');document.getElementById('modalTitle').textContent=p.name;document.getElementById('modalCategory').textContent=(p.category||'PLACE').toUpperCase();document.getElementById('modalLocation').textContent=p.location||city;document.getElementById('modalSummary').textContent=p.description||'';document.getElementById('modalMap').src=p.maps_url||embed(p.name,p.location||city);document.getElementById('modalMapLink').href=p.maps_url||maps(p.name,p.location||city);document.getElementById('modalHistory').textContent=p.history||'Loading the historical story…';document.getElementById('modalPhoto').innerHTML='<div class="modal-photo-loading">Loading featured photo…</div>';document.getElementById('modalGallery').innerHTML='';transport(p);try{const [imgs,h]=await Promise.all([placePhotos(p),fetch('https://en.wikipedia.org/api/rest_v1/page/summary/'+encodeURIComponent(p.name.replace(/ /g,'_'))).then(r=>r.ok?r.json():{}).catch(()=>({}))]);if(!m.classList.contains('open'))return;if(imgs[0]?.url)document.getElementById('modalPhoto').innerHTML=`<img src="${esc(imgs[0].url)}" alt="${esc(p.name)}">`;else document.getElementById('modalPhoto').innerHTML='<div class="image-fallback">✦<span>Photo unavailable</span></div>';document.getElementById('modalGallery').innerHTML=imgs.length>1?imgs.slice(1).map((x,n)=>`<figure><img src="${esc(x.url)}" alt="${esc(p.name)} photo ${n+2}" loading="lazy"><figcaption>${esc(x.source||'Place photo')}</figcaption></figure>`).join(''):'';document.getElementById('modalGallery').hidden=imgs.length<=1;const credit=document.getElementById('photoCredit');if(credit)credit.textContent=imgs[0]?.source==='Wikimedia Commons'?'Photos supplied from Wikimedia Commons when Google Places photos are unavailable.':'Photos supplied by the available place-photo source.';document.getElementById('modalHistory').textContent=p.history||h.extract||'Historical information for this exact place is being curated.'}catch(e){}}
function close(){const m=modal();if(!m)return;m.classList.remove('open');m.style.display='none';m.style.pointerEvents='none';document.body.classList.remove('modal-open');document.body.style.removeProperty('overflow');document.documentElement.style.removeProperty('overflow');document.body.style.removeProperty('cursor');const map=document.getElementById('modalMap');if(map)map.src='about:blank'}
async function init(){cleanPage();if(!city)return;placesCache=await loadPlaces();document.getElementById('cityName').textContent=city;document.getElementById('cityRegion').textContent=cityData?.region?cityData.region+' India':'India';document.getElementById('placeCount').textContent=placesCache.length;document.getElementById('categoryCount').textContent=new Set(placesCache.map(p=>p.category)).size;document.getElementById('cityIntro').textContent=`Explore ${placesCache.length} places across history, forts, nature, culture, food, adventure and famous landmarks.`;document.getElementById('cityHistory').textContent=typeof cityStoryFallback!=='undefined'&&cityStoryFallback[city]?cityStoryFallback[city]:'Explore the architecture, communities, landscapes and traditions that shaped this destination.';await render();document.getElementById('placeSearch').addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('.city-place-card').forEach(c=>c.hidden=q&&!c.dataset.name.includes(q))});document.getElementById('modalClose').onclick=e=>{e.preventDefault();e.stopPropagation();close()};document.getElementById('modalBackdrop').onclick=e=>{e.preventDefault();close()};document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});window.addEventListener('pageshow',cleanPage)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();