/* UnseenGo AI — production AI planner bridge.
 * Gemini output is explicitly labeled AI-generated and is constrained to verified candidates.
 */
(function(){'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function generateAI(result,prefs){
  if(!result?.recommendations?.length)return null;
  const payload={city:prefs.city||result.city,days:prefs.days,interests:prefs.interests,budget:prefs.budget,pace:prefs.pace,places:result.recommendations.map(p=>({name:p.name,city:p.city||result.city,category:p.category,description:p.description||'',latitude:p.latitude,longitude:p.longitude,verification:p.verification}))};
  const r=await fetch('/api/ai-itinerary',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});
  const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'AI planner unavailable');return data;
}
function renderAI(data){const box=document.getElementById('itinerary');if(!box||!data?.itinerary)return;const x=data.itinerary;const days=Array.isArray(x.days)?x.days:[];box.innerHTML='<div class="route-meta"><span>✦ AI-GENERATED ITINERARY</span><span>Candidate places restricted to verified UnseenGo data</span></div>'+days.map(d=>`<article class="day"><h3>DAY ${esc(d.day)} · ${esc(d.title||'Your journey')}</h3><div class="day-place"><div class="time">MORNING</div><div><b>${esc(d.morning||'')}</b></div></div><div class="day-place"><div class="time">AFTERNOON</div><div><b>${esc(d.afternoon||'')}</b></div></div><div class="day-place"><div class="time">EVENING</div><div><b>${esc(d.evening||'')}</b></div></div><p class="note">Estimated budget: ${esc(d.estimatedBudget||'Not provided')}</p></article>`).join('');const msg=document.getElementById('plannerMessage');if(msg){msg.textContent='✓ AI itinerary generated by Gemini using verified UnseenGo candidate places. Live Google data remains separately labeled.';msg.dataset.type='info';}}
function install(){if(!window.UnseenGoAI||window.UnseenGoAI.__liveAIWrapped)return;const original=window.UnseenGoAI.generate?.bind(window.UnseenGoAI);if(!original)return;window.UnseenGoAI.generate=function(){const result=original(...arguments);window.UnseenGoLastResult=result;const prefs=window.UnseenGoPlannerPrefs||arguments[1]||{};setTimeout(async()=>{try{const data=await generateAI(result,prefs);window.UnseenGoAI.lastAI=data;renderAI(data);}catch(e){console.info('Gemini unavailable; keeping deterministic verified itinerary',e.message);const msg=document.getElementById('plannerMessage');if(msg)msg.textContent='✓ Verified UnseenGo itinerary shown. Gemini AI is unavailable until its server key is configured.';}},50);return result;};window.UnseenGoAI.__liveAIWrapped=true;}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,500));else setTimeout(install,500);
})();
