/* UnseenGo AI — Phase 2D authenticated traveller reviews */
(function(){
  const client=()=>window.unseenGoSupabase||null,params=new URLSearchParams(location.search),city=params.get('city')||'';
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const stars=n=>{n=Math.max(1,Math.min(5,Number(n)||0));return '★'.repeat(n)+'☆'.repeat(5-n)};
  async function session(){const sb=client();if(!sb)return null;const {data}=await sb.auth.getSession();return data.session||null}
  async function listReviews(){const sb=client();if(!sb||!city)return[];const {data,error}=await sb.from('reviews').select('id,city,place_name,reviewer_name,rating,review_text,created_at').eq('city',city).order('created_at',{ascending:false}).limit(30);if(error){console.warn(error.message);return[]}return data||[]}
  function render(rs){const host=document.getElementById('localReviews');if(!host)return;if(!rs.length){host.innerHTML='<div class="review-empty-state"><span>✦</span><p>No traveller reviews yet. Be the first to share what you discovered.</p></div>';return}host.innerHTML=rs.map(r=>`<article class="traveller-review"><div class="review-head"><div class="review-author"><b>${esc(r.reviewer_name)}</b>${r.place_name?`<small>Visited: ${esc(r.place_name)}</small>`:''}</div><span class="review-stars">${stars(r.rating)}</span></div><p>${esc(r.review_text)}</p><small class="review-date">${esc(r.created_at?new Date(r.created_at).toLocaleDateString(): '')}</small></article>`).join('')}
  async function refresh(){render(await listReviews())}
  async function submit(e){e.preventDefault();const sb=client(),form=document.getElementById('reviewForm'),status=document.getElementById('reviewStatus');const s=await session();if(!s){status.textContent='Please login to publish a traveller review.';setTimeout(()=>location.href='login.html',800);return false}const rating=Number(document.getElementById('reviewRating').value),text=document.getElementById('reviewText').value.trim(),place=document.getElementById('reviewPlace')?.value.trim()||null;if(!city||!Number.isInteger(rating)||rating<1||rating>5||text.length<10||text.length>1000){status.textContent='Choose a 1–5 rating and write 10–1000 characters.';return false}const name=s.user.user_metadata?.full_name||s.user.email?.split('@')[0]||'Traveller';status.textContent='Publishing your review…';const {error}=await sb.from('reviews').insert({city,place_name:place,reviewer_name:name,rating,review_text:text,user_id:s.user.id});if(error){console.error(error);status.textContent='Could not publish the review. If this is your first authenticated review, run the Phase 2D auth-reviews SQL migration.';return false}form.reset();form.classList.remove('open');status.textContent='Review published successfully. Thank you!';await refresh();return false}
  function init(){const form=document.getElementById('reviewForm');if(!form)return;form.onsubmit=submit;session().then(s=>{const b=document.querySelector('.traveller-feedback button');if(b&&!s)b.textContent='Login to write a review ✦'});refresh()}
  window.UnseenGoReviews={refresh,submit};if(document.readyState==='loading')addEventListener('DOMContentLoaded',init,{once:true});else init();addEventListener('unseengo:supabase-ready',refresh)
})();
