/* UnseenGo AI — route-aware itinerary engine
 * Uses supplied coordinates, visit duration and opening hours only.
 * Travel time is an explainable estimate, not live traffic data.
 */
(function(){'use strict';
 const R=6371;
 const num=v=>Number.isFinite(Number(v))?Number(v):null;
 function distanceKm(a,b){if(!a||!b||num(a.lat)===null||num(a.lng)===null||num(b.lat)===null||num(b.lng)===null)return null;const p=Math.PI/180,dLat=(b.lat-a.lat)*p,dLng=(b.lng-a.lng)*p;const x=Math.sin(dLat/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(dLng/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
 function travelMinutes(km){if(km===null)return null;const speed=km<5?25:km<25?40:km<80?55:65;return Math.max(5,Math.round(km/speed*60))}
 function parseTime(v){if(!v)return null;const m=String(v).match(/^(\d{1,2}):(\d{2})/);if(!m)return null;return Number(m[1])*60+Number(m[2])}
 function openWindow(p){const open=parseTime(p.openingTime||p.open_time),close=parseTime(p.closingTime||p.closing_time);return open!==null&&close!==null?{open,close}:null}
 function isOpenAt(p,minute){const w=openWindow(p);return !w||minute>=w.open&&minute<=w.close}
 function nextOpen(p,minute){const w=openWindow(p);if(!w||minute<=w.close)return minute;if(w.open!==null)return w.open+1440;return minute}
 function optimize(recs,days=1,pace='balanced',avoid=[]){const available=(recs||[]).filter(p=>num(p.lat)!==null&&num(p.lng)!==null);if(!available.length)return{places:recs||[],days:[],optimized:false,reason:'Coordinates are not available for the supplied destinations.'};const perDay=pace==='slow'?2:pace==='fast'?4:3;const maxDays=Math.max(1,Math.min(14,Number(days)||1));const ordered=[];let current=null,remaining=available.slice();while(remaining.length){let best=null,bestCost=Infinity;for(const p of remaining){const d=current?distanceKm(current,p):0;const crowdPenalty=avoid.includes('crowds')&&String(p.crowdLevel||'').toLowerCase()==='high'?999:0;const cost=(d||0)+crowdPenalty-(Number(p.unseenScore)||0)*.002;if(cost<bestCost){bestCost=cost;best=p}}ordered.push(best);remaining=remaining.filter(x=>x!==best);current=best}
  const slots=avoid.includes('early')?['09:30 AM','11:30 AM','01:30 PM','03:30 PM','05:30 PM','07:00 PM']:['07:00 AM','09:00 AM','11:00 AM','01:00 PM','03:30 PM','05:30 PM'];
  const daysOut=Array.from({length:Math.min(maxDays,Math.ceil(ordered.length/perDay))},(_,i)=>({day:i+1,places:[]}));let prev=null,clock=avoid.includes('early')?570:420;
  ordered.forEach((p,i)=>{let day=Math.min(daysOut.length-1,Math.floor(i/perDay));if(i&&i%perDay===0)clock=avoid.includes('early')?570:420;const km=prev?distanceKm(prev,p):null;const travel=travelMinutes(km);clock+=(travel||0);const w=openWindow(p);if(w&&clock<w.open)clock=w.open;const visit=Math.max(20,Number(p.visitDurationMinutes||p.visit_duration_minutes)||60);const open=p.openingTime||p.open_time,close=p.closingTime||p.closing_time;const fit=isOpenAt(p,clock);const item={...p,distanceFromPreviousKm:km===null?null:Number(km.toFixed(1)),estimatedTravelMinutes:travel,estimatedVisitMinutes:visit,openingTime:open||null,closingTime:close||null,openingHoursApplied:Boolean(w),withinOpeningHours:fit,time:slots[Math.min(daysOut[day].places.length,slots.length-1)],whyNow:fit?(travel?`Arranged after an estimated ${travel}-minute transfer; opening hours are respected.`:'Placed first because it fits your available time.'):w?'Opening-hours data is supplied but this stop could not fit the current window.':'Placed using preference and route proximity; opening hours were not supplied.'};daysOut[day].places.push(item);clock+=visit;prev=p});return{places:ordered,days:daysOut,optimized:true,reason:'Ordered by shortest-next-leg using supplied coordinates, with supplied opening hours and visit durations applied where available.'}}
 function mapsUrl(places){const names=(places||[]).map(p=>encodeURIComponent(`${p.name}, ${p.city}`));if(!names.length)return'#';const q=new URLSearchParams({api:'1',destination:names.at(-1),travelmode:'driving'});if(names.length>1)q.set('waypoints',names.slice(0,-1).join('|'));return`https://www.google.com/maps/dir/?${q}`}
 window.UnseenGoRoute={distanceKm,travelMinutes,optimize,mapsUrl};
})();