-- UnseenGo AI — Phase 2D Traveller Reviews
-- Run this once in Supabase SQL Editor.

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  city text not null,
  place_name text,
  reviewer_name text not null check (char_length(trim(reviewer_name)) between 2 and 60),
  rating smallint not null check (rating between 1 and 5),
  review_text text not null check (char_length(trim(review_text)) between 10 and 1000),
  created_at timestamptz not null default now()
);

alter table public.reviews enable row level security;

-- Public visitors can read reviews.
drop policy if exists "Public can read reviews" on public.reviews;
create policy "Public can read reviews"
on public.reviews for select
to anon, authenticated
using (true);

-- Public visitors can submit a review.
drop policy if exists "Public can submit reviews" on public.reviews;
create policy "Public can submit reviews"
on public.reviews for insert
to anon, authenticated
with check (
  char_length(trim(reviewer_name)) between 2 and 60
  and rating between 1 and 5
  and char_length(trim(review_text)) between 10 and 1000
);

-- No public update/delete policies are created. Reviews cannot be edited/deleted
-- from the browser in Phase 2D.

grant select, insert on public.reviews to anon, authenticated;
grant usage, select on sequence public.reviews_id_seq to anon, authenticated;
