/* UnseenGo USA Editorial Theme — loaded on every public HTML page. */
(function(){'use strict';
const KEY='unseengo_theme';
function saved(){try{return localStorage.getItem(KEY)||'dark'}catch(e){return'dark'}}
function loadUSATheme(){if(document.querySelector('link[data-ug-usa-theme]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='/Unseen-Go-AI/unseengo-usa-theme.css?v=20260827';l.dataset.ugUsaTheme='1';document.head.appendChild(l)}
function apply(mode){const light=mode==='light';document.documentElement.classList.toggle('ug-light',light);document.documentElement.dataset.theme=mode;const b=document.querySelector('.ug-theme-toggle');if(b){b.querySelector('.ug-theme-icon').textContent=light?'☀':'☾';b.querySelector('.ug-theme-label').textContent=light?'Light':'Dark';b.setAttribute('aria-label',light?'Switch to dark theme':'Switch to light theme');}}
function add(){if(document.querySelector('.ug-theme-toggle'))return;const host=document.querySelector('.nav')||document.querySelector('.top')||document.querySelector('header nav')||document.querySelector('header');if(!host)return;const b=document.createElement('button');b.type='button';b.className='ug-theme-toggle';b.innerHTML='<span class="ug-theme-icon" aria-hidden="true"></span><span class="ug-theme-label"></span>';b.addEventListener('click',function(){const n=document.documentElement.classList.contains('ug-light')?'dark':'light';try{localStorage.setItem(KEY,n)}catch(e){}apply(n)});host.appendChild(b);apply(saved())}
function css(){if(document.getElementById('ug-theme-global'))return;const s=document.createElement('style');s.id='ug-theme-global';s.textContent=`html{color-scheme:dark}.ug-theme-toggle{display:inline-flex!important;align-items:center!important;justify-content:center!important;gap:6px!important;min-width:72px!important;height:36px!important;padding:0 11px!important;margin-left:8px!important;border:1px solid rgba(216,243,106,.38)!important;border-radius:999px!important;background:rgba(216,243,106,.09)!important;color:#d8f36a!important;font:900 10px/1 system-ui,sans-serif!important;cursor:pointer!important;white-space:nowrap!important;z-index:9999!important}.ug-theme-toggle:hover{background:rgba(216,243,106,.18)!important}.ug-theme-icon{font-size:14px!important}.ug-theme-label{font-size:9px!important}@media(max-width:850px){.ug-theme-toggle{min-width:36px!important;width:36px!important;padding:0!important}.ug-theme-label{display:none!important}}`;document.head.appendChild(s)}
loadUSATheme();css();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',add);else add();})();
