/* UnseenGo AI — transport routing + always-visible city transport */
(function(){
'use strict';
const $=id=>document.getElementById(id);let destination='',city='';
function route(mode){const origin=$('transportOrigin')?.value.trim();if(!destination)return;const originText=origin||city||'';const url='https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(originText)+'&destination='+encodeURIComponent(destination+' '+city)+'&travelmode='+encodeURIComponent(mode);if($('directionLink')){$('directionLink').href=url;$('directionLink').textContent='Open '+mode+' route in Google Maps ↗';}}
function pickup(){const q='nearest bus stop OR railway station OR taxi stand near '+destination+' '+city;if($('pickupLink'))$('pickupLink').href='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q);}
function setupModal(){if(!$('placeModal'))return;const observer=new MutationObserver(()=>{const modal=$('placeModal');if(!modal.classList.contains('open'))return;destination=$('modalTitle')?.textContent.trim()||'';city=$('modalLocation')?.textContent.trim()||new URLSearchParams(location.search).get('city')||'';if($('transportDestination'))$('transportDestination').textContent=destination+' · '+city;route(document.querySelector('.transport-mode.active')?.dataset.mode||'driving');pickup();});observer.observe($('placeModal'),{attributes:true,childList:true,subtree:true});document.querySelectorAll('.transport-mode').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.transport-mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');route(b.dataset.mode)}));$('transportOrigin')?.addEventListener('input',()=>route(document.querySelector('.transport-mode.active')?.dataset.mode||'driving'));$('useLocation')?.addEventListener('click',()=>{if(!navigator.geolocation){$('transportOrigin').value='My current location';route('driving');return;}navigator.geolocation.getCurrentPosition(pos=>{$('transportOrigin').value=pos.coords.latitude+','+pos.coords.longitude;route(document.querySelector('.transport-mode.active')?.dataset.mode||'driving')},()=>{$('transportOrigin').focus()},{enableHighAccuracy:true,timeout:8000});});}
function visibleCityTransport(){
 const cityName=new URLSearchParams(location.search).get('city')||'';if(!cityName||document.getElementById('cityTransportVisible'))return;
 const section=document.createElement('section');section.id='cityTransportVisible';section.className='city-section city-transport-visible';
 const e=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 section.innerHTML='<div class="section-head"><div><p class="eyebrow">TRANSPORT</p><h2>Get to <em>'+e(cityName)+'.</em></h2></div><p>Choose a travel mode and check practical connectivity from your pickup point to this city. Live routes, nearby stations and navigation open in Google Maps.</p></div><div class="transport-city-card"><div class="transport-city-route"><label>STARTING POINT</label><div class="transport-start-row"><input id="visibleTransportOrigin" placeholder="Nearest station, bus stand, landmark or pickup point"><button id="visibleUseLocation" type="button">⌖ Use my location</button></div></div><div class="transport-city-destination"><span>DESTINATION</span><strong>'+e(cityName)+'</strong></div><div class="visible-transport-modes"><button data-mode="driving" class="active" type="button">🚗<b>Car / Taxi</b><small>Road route</small></button><button data-mode="transit" type="button">🚌<b>Bus</b><small>Bus connectivity</small></button><button data-mode="transit" type="button">🚆<b>Train</b><small>Rail connectivity</small></button><button data-mode="walking" type="button">🚶<b>Walking</b><small>Where practical</small></button><button data-mode="bicycling" type="button">🚲<b>Bike</b><small>Cycling route</small></button><button data-mode="flight" type="button">✈️<b>Flight</b><small>Nearest airport</small></button><button data-mode="transit" type="button">🚇<b>Metro</b><small>Where available</small></button></div><div class="visible-transport-actions"><a id="visibleRoute" target="_blank" rel="noopener">Open route in Google Maps ↗</a><a id="visibleNearby" target="_blank" rel="noopener">Find nearby transport ↗</a></div><div class="visible-nearby-grid"><a id="visibleRail" target="_blank" rel="noopener">🚆 Nearest railway station</a><a id="visibleBus" target="_blank" rel="noopener">🚌 Nearest bus stand</a><a id="visibleAirport" target="_blank" rel="noopener">✈️ Nearest airport</a><a id="visibleMetro" target="_blank" rel="noopener">🚇 Nearest metro station</a><a id="visibleTaxi" target="_blank" rel="noopener">🚕 Taxi / cab</a><a id="visibleParking" target="_blank" rel="noopener">🅿️ Parking</a></div><p class="transport-disclaimer">Live schedules and availability are not invented. Google Maps opens current route and nearby-search results for the selected city.</p></div>';
 const placeSection=document.getElementById('cityPlaces')?.closest('.city-section');if(placeSection)placeSection.after(section);else document.querySelector('main')?.append(section);
 const style=document.createElement('style');style.textContent='#cityTransportVisible{scroll-margin-top:90px}.transport-city-card{border:1px solid #303b31;border-radius:22px;background:linear-gradient(145deg,#111711,#0b0f0c);padding:24px;box-shadow:0 18px 45px rgba(0,0,0,.18)}.transport-city-route label{display:block;font-size:10px;letter-spacing:1.5px;color:#d8ff4d;font-weight:800;margin-bottom:8px}.transport-start-row{display:flex;gap:10px}.transport-start-row input{flex:1;min-width:0;box-sizing:border-box;background:#0a0e0b;border:1px solid #3a473a;border-radius:11px;color:#edf2eb;padding:13px;outline:none}.transport-start-row input:focus{border-color:#d8ff4d;box-shadow:0 0 0 3px rgba(216,255,77,.07)}.transport-start-row button,.visible-transport-actions a{border:1px solid #3a473a;background:#161d17;color:#dfe7dc;border-radius:11px;padding:12px 14px;cursor:pointer;text-decoration:none}.transport-start-row button:hover,.visible-transport-actions a:hover{border-color:#d8ff4d;color:#0b120c;background:linear-gradient(135deg,#d8ff4d,#65e7cf)}.transport-city-destination{display:flex;align-items:center;justify-content:space-between;border-top:1px solid #293229;border-bottom:1px solid #293229;padding:15px 0;margin:16px 0}.transport-city-destination span{font-size:10px;letter-spacing:1.5px;color:#8f978c}.transport-city-destination strong{font-size:18px;color:#d8ff4d}.visible-transport-modes{display:grid;grid-template-columns:repeat(7,1fr);gap:8px}.visible-transport-modes button{min-height:78px;border:1px solid #303b31;border-radius:13px;background:#121812;color:#cfd8cd;cursor:pointer;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px;transition:.2s}.visible-transport-modes button:hover,.visible-transport-modes button.active{border-color:#d8ff4d;background:linear-gradient(145deg,#1b271b,#142019);transform:translateY(-3px);box-shadow:0 9px 24px rgba(216,255,77,.08)}.visible-transport-modes button b{font-size:11px}.visible-transport-modes button small{font-size:9px;color:#899289}.visible-transport-actions{display:flex;flex-wrap:wrap;gap:10px;margin-top:16px}.visible-nearby-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-top:14px}.visible-nearby-grid a{padding:11px;border:1px solid #303b31;border-radius:10px;text-decoration:none;color:#bdc8bc;font-size:11px;transition:.2s}.visible-nearby-grid a:hover{border-color:#d8ff4d;color:#d8ff4d;background:#172017}.transport-disclaimer{font-size:11px;color:#808a80;line-height:1.55;margin:16px 0 0}@media(max-width:900px){.visible-transport-modes{grid-template-columns:repeat(4,1fr)}}@media(max-width:650px){.transport-start-row{flex-direction:column}.visible-transport-modes{grid-template-columns:repeat(2,1fr)}.visible-nearby-grid{grid-template-columns:1fr}.transport-city-destination{align-items:flex-start;gap:8px;flex-direction:column}}';document.head.appendChild(style);
 const origin=document.getElementById('visibleTransportOrigin'),routeLink=document.getElementById('visibleRoute'),nearbyLink=document.getElementById('visibleNearby');let mode='driving';
 function update(){const o=origin.value.trim();routeLink.href='https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(cityName)+(o?'&origin='+encodeURIComponent(o):'')+'&travelmode='+encodeURIComponent(mode==='flight'?'driving':mode);const type=mode==='transit'?'bus and train stations':mode==='bicycling'?'bike rental and cycling':mode==='walking'?'walking routes':mode==='flight'?'airport':mode==='driving'?'taxi and car rental':'transport';nearbyLink.href='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(type+' near '+cityName);[['visibleRail','railway station'],['visibleBus','bus stand'],['visibleAirport','airport'],['visibleMetro','metro station'],['visibleTaxi','taxi cab'],['visibleParking','parking']].forEach(([id,type])=>document.getElementById(id).href='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(type+' near '+cityName));}
 section.querySelectorAll('.visible-transport-modes button').forEach(b=>b.addEventListener('click',()=>{section.querySelectorAll('.visible-transport-modes button').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode;update()}));origin.addEventListener('input',update);document.getElementById('visibleUseLocation').addEventListener('click',()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>{origin.value=p.coords.latitude+','+p.coords.longitude;update()},()=>origin.focus()):origin.focus());update();
}
function init(){setupModal();visibleCityTransport();setTimeout(visibleCityTransport,300);setTimeout(visibleCityTransport,1200);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();

/* Place-card visual repair: shared by every place on every city page. */
(function(){
'use strict';
function addPlaceCardStyles(){
 if(document.getElementById('unseengo-place-card-fix'))return;
 const s=document.createElement('style');s.id='unseengo-place-card-fix';s.textContent=`
.city-place-grid{align-items:stretch}
.city-place-card{position:relative;isolation:isolate;min-width:0;display:flex;flex-direction:column;background:linear-gradient(145deg,#111711,#0c100d);border:1px solid rgba(180,205,150,.18);box-shadow:0 8px 24px rgba(0,0,0,.16);transition:transform .28s cubic-bezier(.2,.7,.2,1),border-color .28s ease,box-shadow .28s ease,background .28s ease}
.city-place-card::after{content:"";position:absolute;inset:0;border-radius:inherit;background:radial-gradient(circle at 85% 8%,rgba(216,255,77,.14),transparent 34%);opacity:0;pointer-events:none;transition:opacity .28s ease}
.city-place-card:hover{transform:translateY(-8px);border-color:rgba(216,255,77,.72);background:linear-gradient(145deg,#151d15,#0d120e);box-shadow:0 22px 48px rgba(0,0,0,.38),0 0 0 1px rgba(216,255,77,.08),0 0 32px rgba(216,255,77,.06)}
.city-place-card:hover::after{opacity:1}
.city-place-card:focus-visible{outline:3px solid #d8ff4d;outline-offset:4px}
.city-place-card .place-image{position:relative;flex:0 0 210px;background:linear-gradient(135deg,#151d17,#0c110e);overflow:hidden}
.city-place-card .place-image::after{content:"";position:absolute;inset:0;background:linear-gradient(180deg,transparent 55%,rgba(0,0,0,.18));pointer-events:none}
.city-place-card .place-image img{transition:transform .55s cubic-bezier(.2,.7,.2,1),filter .35s ease;will-change:transform}
.city-place-card:hover .place-image img{transform:scale(1.07);filter:saturate(1.06) contrast(1.03)}
.city-place-card .place-card-body{position:relative;z-index:1;display:flex;flex:1;flex-direction:column;padding:20px}
.city-place-card .place-card-body h3{transition:color .25s ease,text-shadow .25s ease,transform .25s ease}
.city-place-card:hover .place-card-body h3{color:#d8ff4d;text-shadow:0 0 14px rgba(216,255,77,.22);transform:translateX(2px)}
.city-place-card .place-location{margin-top:auto;padding-top:12px}
.city-place-card .details-button{display:inline-flex;align-items:center;gap:7px;margin-top:14px;padding:9px 0;color:#d8ff4d;transition:transform .22s ease,text-shadow .22s ease}
.city-place-card .details-button::after{content:"→";transition:transform .22s ease}
.city-place-card:hover .details-button{transform:translateX(3px);text-shadow:0 0 12px rgba(216,255,77,.25)}
.city-place-card:hover .details-button::after{transform:translateX(4px)}
.image-fallback,.google-photo-unavailable{min-height:210px;background:linear-gradient(145deg,#151d17,#0c110e);color:#9aa49a}
@media(max-width:650px){.city-place-card:hover{transform:translateY(-4px)}.city-place-card .place-image{flex-basis:200px}}
`;
 document.head.appendChild(s);
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',addPlaceCardStyles,{once:true});else addPlaceCardStyles();
})();