/* UnseenGo AI — transport database
 * The UI reads this dataset first. Each record is a known transport hub.
 * Cities not yet represented use a Google Maps live nearby-search fallback.
 */
(function(){
'use strict';
const D={
  Kurnool:{bus:[['Kurnool Bus Station','APSRTC / intercity bus hub']],train:[['Kurnool City Railway Station','South Central Railway']],airport:[['Uyyalawada Narasimha Reddy Airport','Orvakal · about 18 km from Kurnool']],metro:[],taxi:[['Kurnool Taxi / Cab Pickup','Kurnool city']],parking:[['Kurnool City Parking','Kurnool city']]},
  Hyderabad:{bus:[['MGBS — Mahatma Gandhi Bus Station','Intercity / interstate buses'],['Jubilee Bus Station','JBS / Secunderabad'],['Koti Bus Station','Central Hyderabad']],train:[['Secunderabad Junction','Major rail terminal'],['Hyderabad Deccan (Nampally)','Major rail terminal'],['Kacheguda Railway Station','Major rail station']],airport:[['Rajiv Gandhi International Airport','Shamshabad']],metro:[['MGBS Metro Station','Red / Green interchange'],['Ameerpet Metro Station','Red / Blue interchange'],['JBS Parade Ground Metro Station','Green Line / interchange']],taxi:[['MGBS Taxi Pickup','Central Hyderabad']],parking:[['MGBS Parking','Central Hyderabad']]},
  Bengaluru:{bus:[['Kempegowda Bus Station (Majestic)','Major city and intercity bus hub'],['Shanthinagar Bus Station','City / intercity services'],['Yeshwanthpur Bus Station','North-west Bengaluru']],train:[['KSR Bengaluru City Railway Station','Major rail terminal'],['Yesvantpur Junction','Major rail station'],['Kengeri Railway Station','Suburban rail']],airport:[['Kempegowda International Airport','Devanahalli']],metro:[['Nadaprabhu Kempegowda Station (Majestic)','Green / Purple interchange'],['Krantivira Sangolli Rayanna Railway Station Metro','Purple Line'],['Yeshwanthpur Metro Station','Green Line']],taxi:[['Majestic Cab Pickup','Central Bengaluru']],parking:[['Majestic Parking','Central Bengaluru']]},
  Chennai:{bus:[['CMBT / Puratchi Thalaivar Dr. M.G.R. Bus Terminus','Intercity bus hub'],['Kilambakkam Kalaignar Centenary Bus Terminus','South Chennai intercity hub'],['Broadway Bus Terminus','Central Chennai']],train:[['Chennai Central Railway Station','Major rail terminal'],['Chennai Egmore Railway Station','Major rail terminal'],['Tambaram Railway Station','Suburban rail']],airport:[['Chennai International Airport','Meenambakkam']],metro:[['Chennai Central Metro','Blue / Green connectivity'],['Airport Metro Station','Blue Line'],['Koyambedu Metro Station','Chennai Metro']],taxi:[['Chennai Central Cab Pickup','Central Chennai']],parking:[['Chennai Central Parking','Central Chennai']]},
  Mumbai:{bus:[['Mumbai Central Bus Station','Intercity bus hub'],['Dadar Bus Depot','Central Mumbai'],['Borivali Bus Depot','Western suburbs']],train:[['Mumbai Central','Major rail terminal'],['Chhatrapati Shivaji Maharaj Terminus','Major rail terminal'],['Bandra Terminus','Long-distance rail']],airport:[['Chhatrapati Shivaji Maharaj International Airport','Mumbai']],metro:[['Andheri Metro Station','Mumbai Metro'],['Ghatkopar Metro Station','Mumbai Metro'],['Dahisar East Metro Station','Mumbai Metro']],taxi:[['Mumbai Central Cab Pickup','Central Mumbai']],parking:[['Mumbai Central Parking','Central Mumbai']]},
  Pune:{bus:[['Swargate Bus Station','Major intercity bus hub'],['Pune Station Bus Stand','Central Pune'],['Shivajinagar Bus Stand','North-west Pune']],train:[['Pune Junction','Major rail station'],['Shivajinagar Railway Station','Suburban / passenger rail']],airport:[['Pune Airport','Lohegaon']],metro:[['Shivajinagar Metro Station','Pune Metro'],['Civil Court Metro Station','Interchange']],taxi:[['Pune Station Cab Pickup','Central Pune']],parking:[['Swargate Parking','Central Pune']]},
  Kolkata:{bus:[['Esplanade Bus Terminus','Central Kolkata'],['Karunamoyee Bus Terminal','Salt Lake'],['Babughat Bus Stand','Central Kolkata']],train:[['Howrah Junction','Major rail terminal'],['Sealdah Railway Station','Major rail terminal']],airport:[['Netaji Subhas Chandra Bose International Airport','Kolkata']],metro:[['Esplanade Metro Station','Kolkata Metro'],['Sealdah Metro Station','Kolkata Metro'],['Howrah Metro Station','Kolkata Metro']],taxi:[['Esplanade Taxi Pickup','Central Kolkata']],parking:[['Esplanade Parking','Central Kolkata']]},
  Jaipur:{bus:[['Sindhi Camp Bus Stand','Major intercity bus hub'],['Narayan Singh Circle Bus Stand','City / intercity services']],train:[['Jaipur Junction','Major rail station'],['Gandhi Nagar Jaipur Railway Station','Rail station']],airport:[['Jaipur International Airport','Sanganer']],metro:[['Chandpole Metro Station','Jaipur Metro'],['Sindhi Camp Metro Station','Jaipur Metro'],['Mansarovar Metro Station','Jaipur Metro']],taxi:[['Sindhi Camp Cab Pickup','Central Jaipur']],parking:[['Sindhi Camp Parking','Central Jaipur']]},
  Ahmedabad:{bus:[['Geeta Mandir Bus Stand','Major intercity bus hub'],['Ranip Bus Terminal','North Ahmedabad']],train:[['Ahmedabad Junction (Kalupur)','Major rail terminal'],['Sabarmati Junction','Rail station']],airport:[['Sardar Vallabhbhai Patel International Airport','Ahmedabad']],metro:[['Kalupur Railway Station Metro','Ahmedabad Metro'],['Old High Court Metro Station','Ahmedabad Metro'],['Thaltej Metro Station','Ahmedabad Metro']],taxi:[['Geeta Mandir Cab Pickup','Central Ahmedabad']],parking:[['Geeta Mandir Parking','Central Ahmedabad']]},
  Lucknow:{bus:[['Alambagh Bus Stand','Major intercity bus hub'],['Kaiserbagh Bus Station','Central Lucknow']],train:[['Lucknow Charbagh Railway Station','Major rail terminal'],['Gomti Nagar Railway Station','Rail station']],airport:[['Chaudhary Charan Singh International Airport','Lucknow']],metro:[['Charbagh Metro Station','Lucknow Metro'],['Hazratganj Metro Station','Lucknow Metro'],['Munshipulia Metro Station','Lucknow Metro']],taxi:[['Charbagh Cab Pickup','Central Lucknow']],parking:[['Charbagh Parking','Central Lucknow']]},
  Bhubaneswar:{bus:[['Baramunda ISBT','Major intercity bus hub'],['Master Canteen Bus Stand','Central Bhubaneswar']],train:[['Bhubaneswar Railway Station','Major rail station'],['Bhubaneswar New Station','Rail station']],airport:[['Biju Patnaik International Airport','Bhubaneswar']],metro:[],taxi:[['Master Canteen Cab Pickup','Central Bhubaneswar']],parking:[['Bhubaneswar Railway Station Parking','Central Bhubaneswar']]},
  Goa:{bus:[['Kadamba Bus Terminal Panaji','Goa state/intercity bus hub'],['Kadamba Bus Stand Margao','South Goa']],train:[['Madgaon Junction','Major rail station'],['Vasco da Gama Railway Station','Rail station']],airport:[['Manohar International Airport','Mopa'],['Goa International Airport','Dabolim']],metro:[],taxi:[['Panaji Taxi Stand','Panaji'],['Margao Taxi Stand','South Goa']],parking:[['Panaji Bus Terminal Parking','Panaji']]},
  Guwahati:{bus:[['ISBT Guwahati','Intercity bus hub'],['Paltan Bazaar Bus Stand','Central Guwahati']],train:[['Guwahati Railway Station','Major rail terminal'],['Kamakhya Junction','Major rail station']],airport:[['Lokpriya Gopinath Bordoloi International Airport','Guwahati']],metro:[],taxi:[['Paltan Bazaar Cab Pickup','Central Guwahati']],parking:[['Paltan Bazaar Parking','Central Guwahati']]},
  Indore:{bus:[['Sarwate Bus Stand','Major intercity bus hub'],['Gangwal Bus Stand','Central Indore']],train:[['Indore Junction','Major rail station']],airport:[['Devi Ahilya Bai Holkar Airport','Indore']],metro:[['Gandhi Nagar Metro Station','Indore Metro']],taxi:[['Sarwate Cab Pickup','Central Indore']],parking:[['Sarwate Bus Stand Parking','Central Indore']]},
  Kochi:{bus:[['Vyttila Mobility Hub','Major multimodal bus hub'],['Ernakulam KSRTC Bus Station','Central Kochi']],train:[['Ernakulam Junction','Major rail station'],['Ernakulam Town','Rail station']],airport:[['Cochin International Airport','Nedumbassery']],metro:[['Vyttila Metro Station','Kochi Metro'],['M.G. Road Metro Station','Kochi Metro'],['Aluva Metro Station','Kochi Metro']],taxi:[['Vyttila Taxi Pickup','Kochi']],parking:[['Vyttila Mobility Hub Parking','Kochi']]},
  Visakhapatnam:{bus:[['Maddilapalem Bus Station','City/intercity services'],['RTC Complex Bus Station','Central Visakhapatnam']],train:[['Visakhapatnam Junction','Major rail station']],airport:[['Visakhapatnam Airport','Madhurawada area']],metro:[],taxi:[['RTC Complex Cab Pickup','Central Visakhapatnam']],parking:[['RTC Complex Parking','Central Visakhapatnam']]},
  Vijayawada:{bus:[['Pandit Nehru Bus Station','Major APSRTC intercity hub']],train:[['Vijayawada Junction','Major rail terminal']],airport:[['Vijayawada International Airport','Gannavaram']],metro:[],taxi:[['PNBS Cab Pickup','Central Vijayawada']],parking:[['PNBS Parking','Central Vijayawada']]},
  Tirupati:{bus:[['Tirupati Central Bus Station','Major APSRTC hub'],['Alipiri Bus Stand','Tirumala connectivity']],train:[['Tirupati Railway Station','Major rail station'],['Renigunta Junction','Major rail junction']],airport:[['Tirupati Airport','Renigunta']],metro:[],taxi:[['Tirupati Bus Stand Cab Pickup','Central Tirupati']],parking:[['Tirupati Central Bus Station Parking','Central Tirupati']]}
};
const aliases={Bangalore:'Bengaluru',Bengaluru:'Bengaluru',Bombay:'Mumbai',Calcutta:'Kolkata'};
function key(city){return D[city]?city:(aliases[city]&&D[aliases[city]]?aliases[city]:city)}
function get(city,type){return (D[key(city)]?.[type]||[]).map(x=>({name:x[0],detail:x[1],city:key(city),source:'UnseenGo transport database'}));}
window.UnseenGoTransport={get,cities:Object.keys(D)};
})();