/* UnseenGo AI — explainable hidden-gem recommendation engine */
(function(){'use strict';
 const CATEGORY_MAP={heritage:'Heritage',history:'Heritage',temple:'Heritage',forts:'Heritage',architecture:'Heritage',nature:'Nature',wildlife:'Nature',outdoors:'Nature',photography:'Nature',scenic:'Nature',food:'Food',localfood:'Food',cuisine:'Food',culture:'Culture',arts:'Culture',craft:'Culture',adventure:'Adventure',trekking:'Adventure',sports:'Adventure'};
 const normalise=v=>String(v||'').trim().toLowerCase().replace(/[^a-z0-9]/g,'');
 function getCities(){try{if(typeof cities==='object'&&cities)return cities}catch(_){}return window.cities&&typeof window.cities==='object'?window.cities:{}}
 function getCityNames(){return Object.keys(getCities()).sort((a,b)=>a.localeCompare(b))}
 function parsePlace(row,category,city){const r=Array.isArray(row)?row:[];return{name:String(r[0]||'Unnamed destination'),location:String(r[1]||city),baseScore:Number(r[2])||70,description:String(r[3]||'A distinctive local experience.'),category,city,lat:Number(r[4])||null,lng:Number(r[5])||null,verification:r[6]&&typeof r[6]==='object'?r[6]:null}}
 function collectPlaces(city){const data=getCities()[city];if(!data||typeof data!=='object')return[];return Object.entries(data).filter(([k,v])=>k!=='region'&&Array.isArray(v)).flatMap(([cat,rows])=>rows.map(r=>parsePlace(r,cat,city)))}
 function scoreBreakdown(place,p={}){const selected=(p.interests||[]).map(v=>CATEGORY_MAP[normalise(v)]||String(v));const avoid=p.avoid||[];const interest=selected.length===0?75:selected.includes(place.category)?100:42;let access=75,budget=80;let avoidPenalty=0;if(avoid.includes('long-travel'))access-=15;if(avoid.includes('high-cost'))budget-=12;if(avoid.includes('tourist-traps')&&place.baseScore>=95)avoidPenalty+=8;if(avoid.includes('crowds')&&place.baseScore>=95)avoidPenalty+=10;const pace=p.pace||'balanced';const paceFit=pace==='slow'&&['Nature','Culture','Heritage'].includes(place.category)?95:pace==='fast'&&place.category==='Adventure'?92:78;const hiddenness=Math.min(30,Math.max(12,Math.round(place.baseScore*.30)));const cultural=Math.min(25,Math.max(8,Math.round((place.category==='Heritage'||place.category==='Culture'?96:78)*.25)));const interestPts=Math.round(interest*.20);const accessPts=Math.round(access*.15);const local=Math.round((place.category==='Food'||place.category==='Culture'?92:78)*.10);const score=Math.min(100,Math.max(1,hiddenness+cultural+interestPts+accessPts+local-avoidPenalty));return{score,hiddenness,culturalValue:cultural,interestMatch:interestPts,accessibility:accessPts,localExperience:local,interestPercent:interest,paceFit,budgetFit:Math.max(50,budget),avoidPenalty}}
 function scorePlace(place,p={}){return scoreBreakdown(place,p).score}
 function whyPlace(place,p={},b=scoreBreakdown(place,p)){const mapped=(p.interests||[]).map(v=>CATEGORY_MAP[normalise(v)]||v);const lines=[];if(mapped.includes(place.category))lines.push(`matches your ${place.category.toLowerCase()} interest`);if((p.avoid||[]).includes('crowds'))lines.push('supports your preference to avoid crowded or mainstream places');if((p.avoid||[]).includes('long-travel'))lines.push('is favored by your shorter-travel preference');if((p.avoid||[]).includes('high-cost'))lines.push('fits a cost-conscious plan');if(p.days===1)lines.push('fits a focused one-day plan');if(p.pace==='slow')lines.push('works well with a slower, immersive pace');if(!lines.length)lines.push(`selected for its ${place.category.toLowerCase()} character and discovery signal`);return `Strong match for ${(p.interests||[]).join(' + ')||'your selected interests'}. ${lines.slice(0,3).join('. ')}.`}
 function recommend(city,p={}){const selected=(p.interests||[]).map(v=>CATEGORY_MAP[normalise(v)]||String(v));const places=collectPlaces(city).map(place=>{const breakdown=scoreBreakdown(place,p);return{...place,...breakdown,unseenScore:breakdown.score,why:whyPlace(place,p,breakdown)}}).sort((a,b)=>b.unseenScore-a.unseenScore||b.baseScore-a.baseScore||a.name.localeCompare(b.name));const days=Math.max(1,Math.min(14,Number(p.days)||2));const perDay=p.pace==='slow'?2:p.pace==='fast'?4:3;const target=Math.min(places.length,Math.max(3,days*perDay));const result=[];const cats=new Set();for(const x of places){if(result.length>=target)break;if((!selected.length||selected.includes(x.category))&&!cats.has(x.category)){result.push(x);cats.add(x.category)}}for(const x of places){if(result.length>=target)break;if(!result.includes(x))result.push(x)}return result}
 function buildItinerary(recs,days,pace='balanced'){const d=Math.max(1,Math.min(14,Number(days)||1));const perDay=pace==='slow'?2:pace==='fast'?4:3;const plan=Array.from({length:Math.min(d,Math.max(1,Math.ceil(recs.length/perDay)))},(_,i)=>({day:i+1,places:[]}));recs.forEach((p,i)=>{const day=Math.floor(i/perDay);if(day<plan.length)plan[day].places.push(p)});const slots=['07:00 AM','09:00 AM','11:00 AM','01:00 PM','03:30 PM','05:30 PM'];plan.forEach(day=>day.places.forEach((p,i)=>{p.time=slots[Math.min(i,slots.length-1)];p.whyNow=p.category==='Nature'?'Better light and a calmer outdoor experience.':p.category==='Food'?'A natural local meal stop between discoveries.':p.category==='Heritage'?'Morning or late-afternoon light can make heritage details easier to appreciate.':'A good transition point for the day.'}));return plan}
 function mapsUrl(places){if(!places?.length)return'#';const names=places.map(p=>encodeURIComponent(`${p.name}, ${p.city}`));const q=new URLSearchParams({api:'1',destination:names.at(-1),travelmode:'driving'});if(names.length>1)q.set('waypoints',names.slice(0,-1).join('|'));return`https://www.google.com/maps/dir/?${q}`}
 function generate(city,p={}){const places=collectPlaces(city);if(!city||!places.length)return{city:city||'Unknown destination',recommendations:[],itinerary:[],mapsUrl:'#',summary:'No destination records are available for this city yet.'};const recs=recommend(city,p);const itinerary=buildItinerary(recs,p.days||2,p.pace||'balanced');return{city,recommendations:recs,itinerary,mapsUrl:mapsUrl(recs),requestedDays:Number(p.days)||2,actualDays:itinerary.length,summary:`${itinerary.length}-day ${p.pace||'balanced'} trip · ${p.budget||'medium'} budget · ${(p.interests||[]).join(', ')||'mixed interests'}`}}
 function parseNaturalLanguage(text){const q=String(text||'').toLowerCase();const interests=[];if(/heritage|history|temple|fort|architecture/.test(q))interests.push('Heritage');if(/nature|photograph|photography|sunset|scenic|quiet/.test(q))interests.push('Nature');if(/food|cuisine|breakfast|lunch/.test(q))interests.push('Food');if(/culture|craft|artisan|festival/.test(q))interests.push('Culture');if(/adventure|trek|hike/.test(q))interests.push('Adventure');const avoid=[];if(/crowd|crowded|busy|tourist trap/.test(q))avoid.push('crowds');if(/long travel|far away|too much travel/.test(q))avoid.push('long-travel');if(/expensive|high cost|costly/.test(q))avoid.push('high-cost');if(/tourist trap/.test(q))avoid.push('tourist-traps');const days=Number((q.match(/(\d+)\s*day/)||[])[1])||2;const pace=/slow|relax|quiet|immersive/.test(q)?'slow':/fast|packed|as much as possible/.test(q)?'fast':'balanced';const budget=/premium|luxury/.test(q)?'high':/cheap|budget|low cost/.test(q)?'low':'medium';const names=getCityNames();const city=names.find(n=>q.includes(n.toLowerCase()))||'';return{city,interests:[...new Set(interests)],avoid:[...new Set(avoid)],days,pace,budget}}
 window.UnseenGoAI={getCityNames,collectPlaces,scoreBreakdown,scorePlace,recommend,buildItinerary,mapsUrl,generate,parseNaturalLanguage,parsePlace};
})();
