/* UnseenGo AI — Real weather layer (Open-Meteo, no fabricated weather data). */
(function(){'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const css='.ug-weather{margin:24px 0;padding:18px;border:1px solid #2b372d;border-radius:18px;background:#0d150f}.ug-weather-head{display:flex;justify-content:space-between;gap:12px;align-items:center}.ug-weather-head b{color:#fff;font-size:12px}.ug-weather-head span{color:#849087;font-size:9px}.ug-weather-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:12px}.ug-weather-day{padding:12px;border:1px solid #29362c;border-radius:12px;background:#101711}.ug-weather-day b{display:block;color:#d8ff4d;font-size:10px}.ug-weather-day strong{display:block;color:#fff;font-size:18px;margin-top:5px}.ug-weather-day small{display:block;color:#7f8b80;font-size:9px;margin-top:4px}.ug-weather-note{margin:10px 0 0;color:#68746a;font-size:9px;line-height:1.4}@media(max-width:700px){.ug-weather-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:420px){.ug-weather-grid{grid-template-columns:1fr 1fr}.ug-weather-day{padding:10px}}';
function style(){if(document.getElementById('ug-weather-style'))return;const s=document.createElement('style');s.id='ug-weather-style';s.textContent=css;document.head.appendChild(s)}
async function geocode(city){const u='https://geocoding-api.open-meteo.com/v1/search?name='+encodeURIComponent(city+', India')+'&count=1&language=en&format=json';const r=await fetch(u);if(!r.ok)throw new Error('Weather geocoding failed');const j=await r.json();return j.results?.[0]||null}
async function forecast(lat,lon){const u='https://api.open-meteo.com/v1/forecast?latitude='+encodeURIComponent(lat)+'&longitude='+encodeURIComponent(lon)+'&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=auto&forecast_days=4';const r=await fetch(u);if(!r.ok)throw new Error('Weather forecast failed');return r.json()}
function label(code){const m={0:'Clear sky',1:'Mainly clear',2:'Partly cloudy',3:'Overcast',45:'Fog',48:'Rime fog',51:'Light drizzle',53:'Drizzle',55:'Dense drizzle',61:'Light rain',63:'Rain',65:'Heavy rain',71:'Light snow',73:'Snow',75:'Heavy snow',80:'Rain showers',81:'Rain showers',82:'Heavy showers',95:'Thunderstorm',96:'Thunderstorm + hail',99:'Thunderstorm + hail'};return m[code]||'Weather'}
function card(){let el=document.getElementById('ugWeather');if(el)return el;const hero=document.querySelector('.hero');if(!hero)return null;el=document.createElement('section');el.id='ugWeather';el.className='ug-weather';hero.insertAdjacentElement('afterend',el);return el}
async function load(city){if(!city)return;const el=card();if(!el)return;el.innerHTML='<div class="ug-weather-head"><b>✦ LIVE WEATHER</b><span>Fetching current forecast…</span></div>';try{const loc=await geocode(city);if(!loc)throw new Error('City not found');const j=await forecast(loc.latitude,loc.longitude);const days=(j.daily?.time||[]).slice(0,4);el.innerHTML='<div class="ug-weather-head"><b>✦ LIVE WEATHER · '+esc(loc.name)+'</b><span>Open-Meteo</span></div><div class="ug-weather-grid">'+days.map((d,i)=>'<div class="ug-weather-day"><b>'+esc(new Date(d).toLocaleDateString(undefined,{weekday:'short'}))+'</b><strong>'+Math.round(j.daily.temperature_2m_max[i])+'° / '+Math.round(j.daily.temperature_2m_min[i])+'°</strong><small>'+esc(label(j.daily.weather_code[i]))+' · '+(j.daily.precipitation_probability_max?.[i]??0)+'% rain</small></div>').join('')+'</div><p class="ug-weather-note">Live forecast retrieved for the selected city. Forecast conditions can change; UnseenGo does not invent weather values.</p>'}catch(e){el.innerHTML='<div class="ug-weather-head"><b>✦ LIVE WEATHER</b><span>Unavailable</span></div><p class="ug-weather-note">Live weather could not be loaded right now. Please try again later.</p>'}}
function init(){style();const city=document.getElementById('city');if(!city)return;const first=city.value; if(first)load(first);city.addEventListener('change',()=>load(city.value));}
window.UnseenGoWeather={load,geocode,forecast};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();})();
